var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=(a,b)=>{throw b;},ca="object"==typeof window,k="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ea,fa,ha;
if(da){var fs=require("fs"),ia=require("path");l=k?ia.dirname(l)+"/":__dirname+"/";ea=(a,b)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ha=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};fa=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ia.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===
a||a instanceof ja||a.context instanceof ja))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ba=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(ca||k)k?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
k&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var n=f.print||console.log.bind(console),r=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.quit&&(ba=f.quit);var ka;f.wasmBinary&&(ka=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&v("no native wasm support detected");var la,w=!1,ma,y,z,na,oa,B,C,pa,qa;function ra(){var a=la.buffer;f.HEAP8=y=new Int8Array(a);f.HEAP16=na=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=z=new Uint8Array(a);f.HEAPU16=oa=new Uint16Array(a);f.HEAPU32=C=new Uint32Array(a);f.HEAPF32=pa=new Float32Array(a);f.HEAPF64=qa=new Float64Array(a)}var sa,ta=[],ua=[],va=[],wa=[];function xa(){var a=f.preRun.shift();ta.unshift(a)}
var D=0,ya=null,za=null;function v(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";r(a);w=!0;ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Aa(a){return a.startsWith("data:application/octet-stream;base64,")}var E;E="module.wasm";if(!Aa(E)){var Ba=E;E=f.locateFile?f.locateFile(Ba,l):l+Ba}function Ca(a){try{if(a==E&&ka)return new Uint8Array(ka);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){v(b)}}
function Da(a){if(!ka&&(ca||k)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ca(a));if(fa)return new Promise((b,c)=>{fa(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ca(a))}function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r("failed to asynchronously prepare wasm: "+d);v(d)})}
function Fa(a,b){var c=E;ka||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||c.startsWith("file://")||da||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r("wasm streaming compile failed: "+e);r("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ga(a){for(;0<a.length;)a.shift()(f)}f.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a>>0];case "i8":return y[a>>0];case "i16":return na[a>>1];case "i32":return B[a>>2];case "i64":return B[a>>2];case "float":return pa[a>>2];case "double":return qa[a>>3];case "*":return C[a>>2];default:v(`invalid type for getValue: ${b}`)}};var Ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?F(z,a,b):""}
function Ia(a){this.Ja=a-24;this.Qb=function(b){C[this.Ja+4>>2]=b};this.Pb=function(b){C[this.Ja+8>>2]=b};this.Ga=function(b,c){this.Ob();this.Qb(b);this.Pb(c)};this.Ob=function(){C[this.Ja+16>>2]=0}}var Ja=0,Ka=0,La;La=da?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function Ma(a){a instanceof ja||"unwind"==a||ba(1,a)}function Na(a){ma=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);w=!0}ba(a,new ja(a))}
function Oa(a){if(!w)try{if(a(),!noExitRuntime)try{ma=a=ma,Na(a)}catch(b){Ma(b)}}catch(b){Ma(b)}}function Pa(a){setTimeout(()=>{Oa(a)},1E4)}var Qa=f.preloadPlugins||[],Ra=!1,H=null,I=0,Sa=null,Ta=0,Ua=0,Va=0,J=0,Wa=[],Xa={},Ya,Za,$a,ab=!1,bb=!1,cb=[];
function db(){function a(){bb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!eb){eb=!0;Qa.push({canHandle:function(c){return!f.vc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=new Blob([c],{type:fb(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:fb(d)}));var m=URL.createObjectURL(h),p=new Image;p.onload=()=>{p.complete||v("Image "+
d+" could not be decoded");var q=document.createElement("canvas");q.width=p.width;q.height=p.height;q.getContext("2d").drawImage(p,0,0);URL.revokeObjectURL(m);e&&e(c)};p.onerror=()=>{n("Image "+m+" could not be decoded");g&&g()};p.src=m}});Qa.push({canHandle:function(c){return!f.uc&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){h||(h=!0,e&&e(c))}var h=!1,m=URL.createObjectURL(new Blob([c],{type:fb(d)})),p=new Audio;p.addEventListener("canplaythrough",()=>g(p),!1);
p.onerror=function(){if(!h){r("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",u=0,t=0,x=0;x<c.length;x++)for(u=u<<8|c[x],t+=8;6<=t;){var A=u>>t-6&63;t-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==t?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],q+="=="):4==t&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],q+="=");p.src="data:audio/x-"+d.substr(-3)+
";base64,"+q;g(p)}};p.src=m;Pa(()=>{g(p)})}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!bb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function gb(a,b,c,d){if(b&&f.Qa&&a==f.canvas)return f.Qa;var e;if(b){var g={antialias:!1,alpha:!1,Yb:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof hb&&(e=ib(a,g)))var m=jb[e].Va}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||v("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Qa=m,b&&(L=jb[e],f.Qa=K=L&&L.Va),f.xc=b,cb.forEach(p=>p()),db());return m}var kb=!1,lb=void 0,M=void 0;
function mb(a,b){function c(){ab=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=nb,lb&&d.requestPointerLock(),ab=!0,M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]|8388608),ob(f.canvas),pb()):ob(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),M?("undefined"!=typeof SDL&&(B[SDL.screen>>2]=C[SDL.screen>>2]&-8388609),
ob(f.canvas),pb()):ob(d));if(f.onFullScreen)f.onFullScreen(ab);if(f.onFullscreen)f.onFullscreen(ab)}lb=a;M=b;"undefined"==typeof lb&&(lb=!0);"undefined"==typeof M&&(M=!1);var d=f.canvas;kb||(kb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function nb(){if(!ab)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var qb=0;
function rb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===qb)qb=b+1E3/60;else for(;b+2>=qb;)qb+=1E3/60;setTimeout(a,Math.max(qb-b,0))}}function fb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var sb=0,tb=0,vb=0,wb=0;
function xb(a){if(bb)"mousemove"!=a.type&&"mozMovementX"in a?vb=wb=0:(vb=a.movementX||a.mozMovementX||a.webkitMovementX||0,wb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(sb=SDL.rc+vb,tb=SDL.sc+wb):(sb+=vb,tb+=wb);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,vb=e-sb,wb=a-tb,sb=e,tb=a)}}var yb=[];function pb(){var a=f.canvas;yb.forEach(b=>b(a.width,a.height))}function zb(a,b,c){ob(f.canvas,a,b);c||pb()}
function ob(a,b,c){b&&c?(a.dc=b,a.Wb=c):(b=a.dc,c=a.Wb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}M?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var eb;
function Ab(a,b){Ua=a;Va=b;if(Sa)if(Ra||(Ra=!0),0==a)H=function(){var d=Math.max(0,Za+b-La())|0;setTimeout($a,d)};else if(1==a)H=function(){rb($a)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);k?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}H=function(){setImmediate($a)}}}
function Bb(a,b,c,d,e){!Sa||v("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Sa=a;Ta=d;var g=I;Ra=!1;$a=function(){if(!w)if(0<Wa.length){var h=Date.now(),m=Wa.shift();m.nc(m.hc);if(Ya){var p=Ya,q=0==p%1?p-1:Math.floor(p);Ya=m.kc?q:(8*p+(q+.5))/9}n('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||"Please wait...",
m=Ya,p=Xa.mc,m?m<p?f.setStatus(h+" ("+(p-m)+"/"+p+")"):f.setStatus(h):f.setStatus(""));g<I||setTimeout($a,0)}else if(!(g<I))if(J=J+1|0,1==Ua&&1<Va&&0!=J%Va)H();else{0==Ua&&(Za=La());if(L)for(h=L.Oa,L.Oa=L.Ta,L.Ta=h,h=L.Ka,L.Ka=L.bb,L.bb=h,h=Cb(2097152),m=0;m<=h;++m)L.Ka[m]=0;w||f.preMainLoop&&!1===f.preMainLoop()||(Oa(a),f.postMainLoop&&f.postMainLoop());g<I||("object"==typeof SDL&&SDL.audio&&SDL.audio.ac&&SDL.audio.ac(),H())}};e||(b&&0<b?Ab(0,1E3/b):Ab(1,1),H());if(c)throw"unwind";}
function N(a){return sa.get(a)}var Db=[null,[],[]],Eb=1,O=[],P=[],Fb=[],Gb=[],Q=[],Hb=[],jb=[],Ib=[1,1,2,2,4,4,4,2,3,4,8];function R(a){Jb||(Jb=a)}function Kb(a){for(var b=Eb++,c=a.length;c<b;c++)a[c]=null;return b}function Cb(a){return 32-Math.clz32(0===a?0:a-1)}
function Lb(a){Mb=!1;for(var b=0;b<L.yb;++b){var c=L.Pa[b];if(c.cb&&c.enabled){Mb=!0;var d=c.mb;d=0<d?a*d:c.size*Ib[c.type-5120]*a;var e=Cb(d);var g=L.Oa[e],h=L.Ka[e];L.Ka[e]=L.Ka[e]+1&63;var m=g[h];m?e=m:(m=K.getParameter(34964),g[h]=K.createBuffer(),K.bindBuffer(34962,g[h]),K.bufferData(34962,1<<e,35048),K.bindBuffer(34962,m),e=g[h]);K.bindBuffer(34962,e);K.bufferSubData(34962,0,z.subarray(c.Ja,c.Ja+d));c.Lb.call(K,b,c.size,c.type,c.Db,c.mb,0)}}}
function ib(a,b){a.Ga||(a.Ga=a.getContext,a.getContext=function(d,e){e=a.Ga(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Nb(c,b):0}
function Nb(a,b){var c=Kb(jb),d={pc:c,attributes:b,version:b.Yb,Va:a};a.canvas&&(a.canvas.ec=d);jb[c]=d;("undefined"==typeof b.Ub||b.Ub)&&Ob(d);d.yb=d.Va.getParameter(34921);d.Pa=[];for(a=0;a<d.yb;a++)d.Pa[a]={enabled:!1,cb:!1,size:0,type:0,Db:0,mb:0,Ja:0,Lb:null};a=Cb(2097152);d.Ka=[];d.bb=[];d.Ka.length=d.bb.length=a+1;d.Oa=[];d.Ta=[];d.Oa.length=d.Ta.length=a+1;d.Na=[];d.Na.length=a+1;for(b=0;b<=a;++b){d.Na[b]=null;d.Ka[b]=d.bb[b]=0;d.Oa[b]=[];d.Ta[b]=[];var e=d.Oa[b],g=d.Ta[b];e.length=g.length=
64;for(var h=0;64>h;++h)e[h]=g[h]=null}return c}
function Ob(a){a||(a=L);if(!a.Xb){a.Xb=!0;var b=a.Va;b.lc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.qc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.rb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.rb)b.rb=b.getExtension("EXT_disjoint_timer_query");b.tc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var hb={},Jb,L,Mb;function Pb(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),h=g&&Kb(d);g?(g.name=h,d[h]=g):R(1282);B[b+4*e>>2]=h}}
function Qb(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Rb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Sb(a){a-=5120;return 0==a?y:1==a?z:2==a?na:4==a?B:6==a?pa:5==a||28922==a||28520==a||30779==a||30782==a?C:oa}function Tb(a){var b=K.Tb;if(b){var c=b.Ua[a];"number"==typeof c&&(b.Ua[a]=c=K.getUniformLocation(b,b.Jb[a]+(0<c?"["+c+"]":"")));return c}R(1282)}
function Ub(a,b,c,d){this.id=a;this.y=this.x=0;this.jb=!1;this.Ib=this.Hb=0;this.width=b;this.height=c;this.Gb=b;this.Fb=c;this.title=d;this.attributes=S;this.buttons=0;this.keys=[];this.hb=[];this.pb=this.xb=this.ib=this.Eb=this.Wa=this.gb=this.Bb=this.Mb=this.vb=this.Nb=this.title=null}function Vb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function Wb(a){var b=Vb(a)+1,c=Xb(b);c&&Qb(a,z,c,b);return c}
function Yb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(da)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}v("initRandomDevice")}function Zb(a){return(Zb=Yb())(a)}
var $b=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ac=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$b(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},bc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},cc=a=>
{if("/"===a)return"/";a=ac(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function dc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$b(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var ec=[];function fc(a,b){ec[a]={input:[],output:[],Ma:b};gc(a,hc)}
var hc={open:function(a){var b=ec[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ma.fsync(a.tty)},fsync:function(a){a.tty.Ma.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ma.wb)throw new T(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Ma.wb(a.tty)}catch(m){throw new T(29);}if(void 0===h&&0===e)throw new T(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ma.kb)throw new T(60);
try{for(var e=0;e<d;e++)a.tty.Ma.kb(a.tty,b[c+e])}catch(g){throw new T(29);}d&&(a.node.timestamp=Date.now());return e}},ic={wb:function(a){if(!a.input.length){var b=null;if(da){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(Vb(b)+1);b=Qb(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},kb:function(a,b){null===b||10===b?(n(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(n(F(a.output,0)),a.output=[])}},jc={kb:function(a,b){null===b||10===b?(r(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(r(F(a.output,0)),a.output=[])}},U={Ea:null,Ha:function(){return U.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.Ea||(U.Ea={dir:{node:{Ia:U.Ba.Ia,Fa:U.Ba.Fa,lookup:U.Ba.lookup,$a:U.Ba.$a,rename:U.Ba.rename,unlink:U.Ba.unlink,rmdir:U.Ba.rmdir,readdir:U.Ba.readdir,symlink:U.Ba.symlink},stream:{La:U.Ca.La}},file:{node:{Ia:U.Ba.Ia,Fa:U.Ba.Fa},stream:{La:U.Ca.La,read:U.Ca.read,write:U.Ca.write,ob:U.Ca.ob,zb:U.Ca.zb,Cb:U.Ca.Cb}},link:{node:{Ia:U.Ba.Ia,Fa:U.Ba.Fa,readlink:U.Ba.readlink},stream:{}},qb:{node:{Ia:U.Ba.Ia,
Fa:U.Ba.Fa},stream:kc}});c=lc(a,b,c,d);16384===(c.mode&61440)?(c.Ba=U.Ea.dir.node,c.Ca=U.Ea.dir.stream,c.Aa={}):32768===(c.mode&61440)?(c.Ba=U.Ea.file.node,c.Ca=U.Ea.file.stream,c.Da=0,c.Aa=null):40960===(c.mode&61440)?(c.Ba=U.Ea.link.node,c.Ca=U.Ea.link.stream):8192===(c.mode&61440)&&(c.Ba=U.Ea.qb.node,c.Ca=U.Ea.qb.stream);c.timestamp=Date.now();a&&(a.Aa[b]=c,a.timestamp=c.timestamp);return c},oc:function(a){return a.Aa?a.Aa.subarray?a.Aa.subarray(0,a.Da):new Uint8Array(a.Aa):new Uint8Array(0)},
sb:function(a,b){var c=a.Aa?a.Aa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Aa,a.Aa=new Uint8Array(b),0<a.Da&&a.Aa.set(c.subarray(0,a.Da),0))},bc:function(a,b){if(a.Da!=b)if(0==b)a.Aa=null,a.Da=0;else{var c=a.Aa;a.Aa=new Uint8Array(b);c&&a.Aa.set(c.subarray(0,Math.min(b,a.Da)));a.Da=b}},Ba:{Ia:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.Da:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Rb=4096;b.blocks=Math.ceil(b.size/b.Rb);return b},Fa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.bc(a,b.size)},lookup:function(){throw mc[44];},$a:function(a,b,c,d){return U.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=nc(b,
c)}catch(g){}if(d)for(var e in d.Aa)throw new T(55);}delete a.parent.Aa[a.name];a.parent.timestamp=Date.now();a.name=c;b.Aa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Aa[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=nc(a,b),d;for(d in c.Aa)throw new T(55);delete a.Aa[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Aa)a.Aa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},Ca:{read:function(a,b,c,d,e){var g=a.node.Aa;if(e>=a.node.Da)return 0;a=Math.min(a.node.Da-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===y.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Aa||a.Aa.subarray)){if(g)return a.Aa=b.subarray(c,c+d),a.Da=d;if(0===a.Da&&0===e)return a.Aa=b.slice(c,c+d),a.Da=
d;if(e+d<=a.Da)return a.Aa.set(b.subarray(c,c+d),e),d}U.sb(a,e+d);if(a.Aa.subarray&&b.subarray)a.Aa.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Aa[e+g]=b[c+g];a.Da=Math.max(a.Da,e+d);return d},La:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Da);if(0>b)throw new T(28);return b},ob:function(a,b,c){U.sb(a.node,b+c);a.node.Da=Math.max(a.node.Da,b+c)},zb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new T(43);a=a.node.Aa;if(e&2||a.buffer!==y.buffer){if(0<
c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;v();b=void 0;if(!b)throw new T(48);y.set(a,b)}else c=!1,b=a.byteOffset;return{Ja:b,fc:c}},Cb:function(a,b,c,d){U.Ca.write(a,b,0,d,c,!1);return 0}}};function oc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var pc=null,qc={},rc=[],sc=1,tc=null,uc=!0,T=null,mc={},V=(a,b={})=>{a=dc(a);if(!a)return{path:"",node:null};b=Object.assign({ub:!0,lb:0},b);if(8<b.lb)throw new T(32);a=a.split("/").filter(h=>!!h);for(var c=pc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=nc(c,a[e]);d=ac(d+"/"+a[e]);c.ab&&(!g||g&&b.ub)&&(c=c.ab.root);if(!g||b.tb)for(g=0;40960===(c.mode&61440);)if(c=vc(d),d=dc(bc(d),c),c=V(d,{lb:b.lb+1}).node,40<g++)throw new T(32);}return{path:d,node:c}},wc=a=>{for(var b;;){if(a===
a.parent)return a=a.Ha.Ab,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},xc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%tc.length},nc=(a,b)=>{var c;if(c=(c=yc(a,"x"))?c:a.Ba.lookup?0:2)throw new T(c,a);for(c=tc[xc(a.id,b)];c;c=c.$b){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ba.lookup(a,b)},lc=(a,b,c,d)=>{a=new zc(a,b,c,d);b=xc(a.parent.id,a.name);a.$b=tc[b];return tc[b]=a},Ac=a=>{var b=["r","w","rw"][a&3];
a&512&&(b+="w");return b},yc=(a,b)=>{if(uc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Bc=(a,b)=>{try{return nc(a,b),20}catch(c){}return yc(a,"wx")},Cc=()=>{for(var a=0;4096>=a;a++)if(!rc[a])return a;throw new T(33);},Ec=a=>{Dc||(Dc=function(){this.Ga={}},Dc.prototype={},Object.defineProperties(Dc.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.Ga.flags},
set:function(c){this.Ga.flags=c}},position:{get:function(){return this.Ga.position},set:function(c){this.Ga.position=c}}}));a=Object.assign(new Dc,a);var b=Cc();a.fd=b;return rc[b]=a},kc={open:a=>{a.Ca=qc[a.node.rdev].Ca;a.Ca.open&&a.Ca.open(a)},La:()=>{throw new T(70);}},gc=(a,b)=>{qc[a]={Ca:b}},Fc=(a,b)=>{var c="/"===b,d=!b;if(c&&pc)throw new T(10);if(!c&&!d){var e=V(b,{ub:!1});b=e.path;e=e.node;if(e.ab)throw new T(10);if(16384!==(e.mode&61440))throw new T(54);}b={type:a,wc:{},Ab:b,Zb:[]};a=a.Ha(b);
a.Ha=b;b.root=a;c?pc=a:e&&(e.ab=b,e.Ha&&e.Ha.Zb.push(b))},W=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=cc(a);if(!a||"."===a||".."===a)throw new T(28);var e=Bc(d,a);if(e)throw new T(e);if(!d.Ba.$a)throw new T(63);return d.Ba.$a(d,a,b,c)},Gc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},Hc=(a,b)=>{if(!dc(a))throw new T(44);var c=V(b,{parent:!0}).node;if(!c)throw new T(44);b=cc(b);var d=Bc(c,b);if(d)throw new T(d);if(!c.Ba.symlink)throw new T(63);c.Ba.symlink(c,b,a)},vc=a=>{a=V(a).node;if(!a)throw new T(44);
if(!a.Ba.readlink)throw new T(28);return dc(wc(a.parent),a.Ba.readlink(a))},Jc=(a,b,c)=>{if(""===a)throw new T(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=ac(a);try{e=V(a,{tb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new T(20);}else e=W(a,c,0),d=!0;if(!e)throw new T(44);8192===(e.mode&
61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new T(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ac(b)||b&512)?31:yc(e,Ac(b)):44))throw new T(c);if(b&512&&!d){c=e;c="string"==typeof c?V(c,{tb:!0}).node:c;if(!c.Ba.Fa)throw new T(63);if(16384===(c.mode&61440))throw new T(31);if(32768!==(c.mode&61440))throw new T(28);if(d=yc(c,"w"))throw new T(d);c.Ba.Fa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Ec({node:e,path:wc(e),flags:b,seekable:!0,position:0,Ca:e.Ca,
cc:[],error:!1});e.Ca.open&&e.Ca.open(e);!f.logReadFiles||b&1||(Ic||(Ic={}),a in Ic||(Ic[a]=1));return e},Kc=(a,b,c,d)=>{var e=void 0;if(0>c||0>e)throw new T(28);if(null===a.fd)throw new T(8);if(0===(a.flags&2097155))throw new T(8);if(16384===(a.node.mode&61440))throw new T(31);if(!a.Ca.write)throw new T(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new T(8);if(!a.seekable||!a.Ca.La)throw new T(70);a.position=a.Ca.La(a,0,2);a.cc=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new T(70);
b=a.Ca.write(a,b,0,c,e,d);g||(a.position+=b)},Lc=()=>{T||(T=function(a,b){this.name="ErrnoError";this.node=b;this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(a=>{mc[a]=new T(a);mc[a].stack="<generic error, no stack>"}))},Mc,Nc=()=>{var a="/";a="string"==typeof a?a:wc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=ac(a+"/"+c);try{W(a,16895,0)}catch(d){}}}},Pc=(a,b,c)=>{a=ac("/dev/"+a);var d=oc(!!b,!!c);Oc||(Oc=64);var e=Oc++<<8|0;
gc(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,m,p)=>{for(var q=0,u=0;u<p;u++){try{var t=b()}catch(x){throw new T(29);}if(void 0===t&&0===q)throw new T(6);if(null===t||void 0===t)break;q++;h[m+u]=t}q&&(g.node.timestamp=Date.now());return q},write:(g,h,m,p)=>{for(var q=0;q<p;q++)try{c(h[m+q])}catch(u){throw new T(29);}p&&(g.node.timestamp=Date.now());return q}});Gc(a,d,e)},Oc,Dc,Ic,X=null,Qc=null,Y=null,S=null,Rc={131073:0,131074:0,131075:1,131076:1,131077:1,
131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Sc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Tc(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Uc(a){X&&X.pb&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||N(X.pb)(X.id,a))}function Vc(a,b){if(X){var c=Sc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.hb[a]=b;X.xb&&(d&&(b=2),N(X.xb)(X.id,c,a,b,Tc()))}}}
function Wc(){Xc()}function Yc(){Xc()}function Zc(a){Vc(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function $c(a){Vc(a.keyCode,0)}function ad(){if(X)for(var a=0;a<X.hb.length;++a)X.hb[a]&&Vc(a,0)}function bd(a){X&&(xb(a),a.target==f.canvas&&X.gb&&X.gb&&N(X.gb)(X.id,sb,tb))}function cd(a){X&&a.target==f.canvas&&X.Wa&&N(X.Wa)(X.id,1)}function dd(a){X&&a.target==f.canvas&&X.Wa&&N(X.Wa)(X.id,0)}
function ed(a,b){if(X&&(xb(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.Bb&&N(X.Bb)(X.id,c,b,Tc())}}function fd(a){X&&ed(a,1)}function gd(a){X&&ed(a,0)}
function hd(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.Eb&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;N(X.Eb)(X.id,b,c);a.preventDefault()}}
var Z={},jd=[],kd=null;
function Xc(){if(J!==kd||!J){jd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];kd=J;for(var a=0;a<jd.length;++a){var b=jd[a];if(b){Z[a]||(n("glfw joystick connected:",a),Z[a]={id:Wb(b.id),jc:b.buttons.length,ic:b.axes.length,buttons:Xb(b.buttons.length),axes:Xb(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)y[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)pa[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(n("glfw joystick disconnected",
a),ld(Z[a].id),ld(Z[a].buttons),ld(Z[a].axes),delete Z[a])}}}
function md(a){function b(m){var p="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=t=>{if(2!=q.readyState)++g,n("failed to read dropped file: "+m.name+": "+q.error);else{var x=new Uint8Array(t.target.result);t={};t.flags=t.flags||577;var A=Jc(p,t.flags,t.mode);if("string"==typeof x){var ub=new Uint8Array(Vb(x)+1);x=Qb(x,ub,0,ub.length);Kc(A,ub,x,t.Sb)}else if(ArrayBuffer.isView(x))Kc(A,x,x.byteLength,t.Sb);else throw Error("Unsupported data type");if(null===A.fd)throw new T(8);
A.Vb&&(A.Vb=null);try{A.Ca.close&&A.Ca.close(A)}catch(vd){throw vd;}finally{rc[A.fd]=null}A.fd=null;if(++g===e){N(X.ib)(X.id,e,c);for(t=0;t<d.length;++t)ld(d[t]);ld(c)}}};q.readAsArrayBuffer(m);var u=Wb(p);d.push(u);C[c+4*h>>2]=u}if(X&&X.ib&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Xb(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Nc();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}
function nd(a){if(X&&X.ib)return a.preventDefault(),!1}f.requestFullscreen=function(a,b){mb(a,b)};f.requestAnimationFrame=function(a){rb(a)};f.setCanvasSize=function(a,b,c){zb(a,b,c)};f.pauseMainLoop=function(){H=null;I++};f.resumeMainLoop=function(){I++;var a=Ua,b=Va,c=Sa;Sa=null;Bb(c,0,!1,Ta,!0);Ab(a,b);H()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
f.createContext=function(a,b,c,d){return gb(a,b,c,d)};var K;function zc(a,b,c,d){a||(a=this);this.parent=a;this.Ha=a.Ha;this.ab=null;this.id=sc++;this.name=b;this.mode=c;this.Ba={};this.Ca={};this.rdev=d}Object.defineProperties(zc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Lc();tc=Array(4096);Fc(U,"/");W("/tmp",16895,0);
W("/home",16895,0);W("/home/web_user",16895,0);(()=>{W("/dev",16895,0);gc(259,{read:()=>0,write:(d,e,g,h)=>h});Gc("/dev/null",259);fc(1280,ic);fc(1536,jc);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Zb(a).byteLength);return a[--b]};Pc("random",c);Pc("urandom",c);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();
(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);Fc({Ha:()=>{var b=lc(a,"fd",16895,73);b.Ba={lookup:(c,d)=>{var e=rc[+d];if(!e)throw new T(8);c={parent:null,Ha:{Ab:"fake"},Ba:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var od={p:function(a,b,c,d){v(`Assertion failed: ${G(a)}, at: `+[b?G(b):"unknown filename",c,d?G(d):"unknown function"])},m:function(a,b,c){(new Ia(a)).Ga(b,c);Ja=a;Ka++;throw Ja;},I:function(){return!0},q:function(){v("")},L:La,M:function(a,b,c){z.copyWithin(a,b,b+c)},H:function(a){var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=la.buffer;try{la.grow(g.call(e,2147483648,
d)-h.byteLength+65535>>>16);ra();var m=1;break a}catch(p){}m=void 0}if(m)return!0}return!1},T:function(a){eval(G(a))},U:function(a,b,c){a=N(a);Bb(a,b,c)},K:function(){return 52},G:function(){return 70},s:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=C[b>>2],m=C[b+4>>2];b+=8;for(var p=0;p<m;p++){var q=z[h+p],u=Db[a];0===q||10===q?((1===a?n:r)(F(u,0)),u.length=0):u.push(q)}e+=m}C[d>>2]=e;return 0},r:function(a,b){K.attachShader(P[a],Q[b])},b:function(a,b){34962==a?K.Ra=b:34963==a&&(K.Sa=b);35051==
a?K.eb=b:35052==a&&(K.fb=b);K.bindBuffer(a,O[b])},n:function(a,b){K.bindFramebuffer(a,Fb[b])},ga:function(a,b){K.bindTexture(a,Gb[b])},V:function(a){K.bindVertexArray(Hb[a]);a=K.getParameter(34965);K.Sa=a?a.name|0:0},a:function(a,b,c,d){c&&b?K.bufferData(a,z,d,c,b):K.bufferData(a,b,d)},da:function(a){return K.checkFramebufferStatus(a)},N:function(a){K.clear(a)},O:function(a,b,c,d){K.clearColor(a,b,c,d)},y:function(a){K.compileShader(Q[a])},J:function(){var a=Kb(P),b=K.createProgram();b.name=a;b.Za=
b.Xa=b.Ya=0;b.nb=1;P[a]=b;return a},D:function(a){var b=Kb(Q);Q[b]=K.createShader(a);return b},i:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=O[d];e&&(K.deleteBuffer(e),e.name=0,O[d]=null,d==K.Ra&&(K.Ra=0),d==K.Sa&&(K.Sa=0),d==K.eb&&(K.eb=0),d==K.fb&&(K.fb=0))}},ba:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Fb[d];e&&(K.deleteFramebuffer(e),e.name=0,Fb[d]=null)}},C:function(a){if(a){var b=P[a];b?(K.deleteProgram(b),b.name=0,P[a]=null):R(1281)}},k:function(a){if(a){var b=Q[a];
b?(K.deleteShader(b),Q[a]=null):R(1281)}},ca:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Gb[d];e&&(K.deleteTexture(e),e.name=0,Gb[d]=null)}},P:function(a){K.depthFunc(a)},o:function(a,b){K.detachShader(P[a],Q[b])},g:function(a){L.Pa[a].enabled=!1;K.disableVertexAttribArray(a)},aa:function(a,b,c){Lb(b+c);K.drawArrays(a,b,c);Mb&&K.bindBuffer(34962,O[K.Ra])},t:function(a,b,c,d){if(!K.Sa){var e=1*Ib[c-5120]*b;var g=Cb(e);var h=L.Na[g];h?g=h:(h=K.getParameter(34965),L.Na[g]=K.createBuffer(),
K.bindBuffer(34963,L.Na[g]),K.bufferData(34963,1<<g,35048),K.bindBuffer(34963,h),g=L.Na[g]);K.bindBuffer(34963,g);K.bufferSubData(34963,0,z.subarray(d,d+e));d=0}Lb(b);K.drawElements(a,b,c,d);Mb&&K.bindBuffer(34962,O[K.Ra]);K.Sa||K.bindBuffer(34963,null)},Q:function(a){K.enable(a)},d:function(a){L.Pa[a].enabled=!0;K.enableVertexAttribArray(a)},ea:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,Gb[d],e)},j:function(a,b){Pb(a,b,"createBuffer",O)},ia:function(a,b){Pb(a,b,"createFramebuffer",Fb)},ha:function(a,
b){Pb(a,b,"createTexture",Gb)},W:function(a,b){Pb(a,b,"createVertexArray",Hb)},f:function(a,b){return K.getAttribLocation(P[a],G(b))},ja:function(a,b,c,d){a=K.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Qb(a,z,d,b):0;c&&(B[c>>2]=b)},E:function(a,b,c){if(c)if(a>=Eb)R(1281);else if(a=P[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.Za)for(b=0;b<K.getProgramParameter(a,35718);++b)a.Za=Math.max(a.Za,K.getActiveUniform(a,
b).name.length+1);B[c>>2]=a.Za}else if(35722==b){if(!a.Xa)for(b=0;b<K.getProgramParameter(a,35721);++b)a.Xa=Math.max(a.Xa,K.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.Xa}else if(35381==b){if(!a.Ya)for(b=0;b<K.getProgramParameter(a,35382);++b)a.Ya=Math.max(a.Ya,K.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.Ya}else B[c>>2]=K.getProgramParameter(a,b);else R(1281)},v:function(a,b,c,d){a=K.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?Qb(a,z,d,b):0;c&&(B[c>>2]=b)},w:function(a,
b,c){c?35716==b?(a=K.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(Q[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=K.getShaderParameter(Q[a],b):R(1281)},c:function(a,b){b=G(b);if(a=P[a]){var c=a,d=c.Ua,e=c.Kb,g;if(!d)for(c.Ua=d={},c.Jb={},g=0;g<K.getProgramParameter(c,35718);++g){var h=K.getActiveUniform(c,g);var m=h.name;h=h.size;var p=Rb(m);p=0<p?m.slice(0,p):m;var q=c.nb;c.nb+=h;e[p]=[h,q];for(m=0;m<h;++m)d[q]=m,c.Jb[q++]=p}c=a.Ua;d=0;e=b;g=
Rb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Kb[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},F:function(a){a=P[a];K.linkProgram(a);a.Ua=0;a.Kb={}},$:function(a,b,c,d,e,g,h){if(K.eb)K.readPixels(a,b,c,d,e,g,h);else{var m=Sb(g);K.readPixels(a,b,c,d,e,g,m,h>>31-Math.clz32(m.BYTES_PER_ELEMENT))}},A:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?B[d+4*g>>2]:-1;e+=G(B[c+4*g>>2],0>h?void 0:h)}K.shaderSource(Q[a],e)},fa:function(a,b,
c,d,e,g,h,m,p){if(K.fb)K.texImage2D(a,b,c,d,e,g,h,m,p);else if(p){var q=Sb(m);K.texImage2D(a,b,c,d,e,g,h,m,q,p>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else K.texImage2D(a,b,c,d,e,g,h,m,null)},B:function(a,b,c){K.texParameteri(a,b,c)},h:function(a,b){K.uniform1f(Tb(a),b)},u:function(a,b,c,d){b&&K.uniformMatrix4fv(Tb(a),!!c,pa,d>>2,16*b)},l:function(a){a=P[a];K.useProgram(a);K.Tb=a},e:function(a,b,c,d,e,g){var h=L.Pa[a];K.Ra?(h.cb=!1,K.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.Db=d,h.mb=
e,h.Ja=g,h.cb=!0,h.Lb=function(m,p,q,u,t,x){this.vertexAttribPointer(m,p,q,u,t,x)})},z:function(a,b,c,d){K.viewport(a,b,c,d)},Z:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?mb():zb(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<S[139265];e==Y.length&&(d?f.Qa=gb(f.canvas,!0,!0,{antialias:1<S[135181],depth:0<S[135173],stencil:0<S[135174],alpha:0<S[135172]}):db());!f.Qa&&d?g=0:(a=
new Ub(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,X=a,g=a.id)}return g},_:function(){if(Y)return 1;La();S=Rc;Y=[];X=null;Qc="number"==typeof devicePixelRatio&&devicePixelRatio||1;window.addEventListener("gamepadconnected",Wc,!0);window.addEventListener("gamepaddisconnected",Yc,!0);window.addEventListener("keydown",Zc,!0);window.addEventListener("keypress",Uc,!0);window.addEventListener("keyup",$c,!0);window.addEventListener("blur",ad,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+
"dppx)").addEventListener("change",b,{once:!0});Qc="number"==typeof devicePixelRatio&&devicePixelRatio||1;X&&X.Mb&&N(X.Mb)(X.id,Qc,Qc)})();f.canvas.addEventListener("touchmove",bd,!0);f.canvas.addEventListener("touchstart",fd,!0);f.canvas.addEventListener("touchcancel",gd,!0);f.canvas.addEventListener("touchend",gd,!0);f.canvas.addEventListener("mousemove",bd,!0);f.canvas.addEventListener("mousedown",fd,!0);f.canvas.addEventListener("mouseup",gd,!0);f.canvas.addEventListener("wheel",hd,!0);f.canvas.addEventListener("mousewheel",
hd,!0);f.canvas.addEventListener("mouseenter",cd,!0);f.canvas.addEventListener("mouseleave",dd,!0);f.canvas.addEventListener("drop",md,!0);f.canvas.addEventListener("dragover",nd,!0);yb.push((b,c)=>{if(X){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.Hb=X.x,X.Ib=X.y,X.Gb=X.width,X.Fb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.jb=!0):1==X.jb?(X.x=X.Hb,X.y=X.Ib,X.width=X.Gb,X.height=X.Fb,X.jb=!1):X.width!=b||X.height!=
c?(X.width=b,X.height=c):d=!1;d&&(zb(X.width,X.height,!0),X&&X.Nb&&N(X.Nb)(X.id,X.width,X.height),X&&X.vb&&N(X.vb)(X.id,X.width,X.height))}});return 1},X:function(){},R:function(){},S:function(){},Y:function(){window.removeEventListener("gamepadconnected",Wc,!0);window.removeEventListener("gamepaddisconnected",Yc,!0);window.removeEventListener("keydown",Zc,!0);window.removeEventListener("keypress",Uc,!0);window.removeEventListener("keyup",$c,!0);window.removeEventListener("blur",ad,!0);f.canvas.removeEventListener("touchmove",
bd,!0);f.canvas.removeEventListener("touchstart",fd,!0);f.canvas.removeEventListener("touchcancel",gd,!0);f.canvas.removeEventListener("touchend",gd,!0);f.canvas.removeEventListener("mousemove",bd,!0);f.canvas.removeEventListener("mousedown",fd,!0);f.canvas.removeEventListener("mouseup",gd,!0);f.canvas.removeEventListener("wheel",hd,!0);f.canvas.removeEventListener("mousewheel",hd,!0);f.canvas.removeEventListener("mouseenter",cd,!0);f.canvas.removeEventListener("mouseleave",dd,!0);f.canvas.removeEventListener("drop",
md,!0);f.canvas.removeEventListener("dragover",nd,!0);f.canvas.width=f.canvas.height=1;X=Y=null},x:function(a,b){S[a]=b}};
(function(){function a(c){c=c.exports;f.asm=c;la=f.asm.ka;ra();sa=f.asm.ua;ua.unshift(f.asm.la);D--;f.monitorRunDependencies&&f.monitorRunDependencies(D);if(0==D&&(null!==ya&&(clearInterval(ya),ya=null),za)){var d=za;za=null;d()}return c}var b={a:od};D++;f.monitorRunDependencies&&f.monitorRunDependencies(D);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return r("Module.instantiateWasm callback failed with error: "+c),!1}Fa(b,function(c){a(c.instance)});return{}})();
f._updateShaderFunction=function(){return(f._updateShaderFunction=f.asm.ma).apply(null,arguments)};f._setRenderNeeded=function(){return(f._setRenderNeeded=f.asm.na).apply(null,arguments)};f._translateState=function(){return(f._translateState=f.asm.oa).apply(null,arguments)};f._scaleState=function(){return(f._scaleState=f.asm.pa).apply(null,arguments)};f._resizeWindow=function(){return(f._resizeWindow=f.asm.qa).apply(null,arguments)};
f._resetState=function(){return(f._resetState=f.asm.ra).apply(null,arguments)};f._setBRenderMesh=function(){return(f._setBRenderMesh=f.asm.sa).apply(null,arguments)};var pd=f._main=function(){return(pd=f._main=f.asm.ta).apply(null,arguments)},Xb=f._malloc=function(){return(Xb=f._malloc=f.asm.va).apply(null,arguments)},ld=f._free=function(){return(ld=f._free=f.asm.wa).apply(null,arguments)};function qd(){return(qd=f.asm.xa).apply(null,arguments)}
function rd(){return(rd=f.asm.ya).apply(null,arguments)}function sd(){return(sd=f.asm.za).apply(null,arguments)}
f.ccall=function(a,b,c,d){var e={string:q=>{var u=0;if(null!==q&&void 0!==q&&0!==q){u=Vb(q)+1;var t=sd(u);Qb(q,z,t,u);u=t}return u},array:q=>{var u=sd(q.length);y.set(q,u);return u}};a=f["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var p=e[c[m]];p?(0===h&&(h=qd()),g[m]=p(d[m])):g[m]=d[m]}c=a.apply(null,g);return c=function(q){0!==h&&rd(h);return"string"===b?G(q):"boolean"===b?!!q:q}(c)};var td;za=function ud(){td||wd();td||(za=ud)};
function wd(){function a(){if(!td&&(td=!0,f.calledRun=!0,!w)){f.noFSInit||Mc||(Mc=!0,Lc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Pc("stdin",f.stdin):Hc("/dev/tty","/dev/stdin"),f.stdout?Pc("stdout",null,f.stdout):Hc("/dev/tty","/dev/stdout"),f.stderr?Pc("stderr",null,f.stderr):Hc("/dev/tty1","/dev/stderr"),Jc("/dev/stdin",0),Jc("/dev/stdout",1),Jc("/dev/stderr",1));uc=!1;Ga(ua);Ga(va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(xd){var b=pd;try{var c=b(0,0);ma=c;Na(c)}catch(d){Ma(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),wa.unshift(b);Ga(wa)}}if(!(0<D)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();Ga(ta);0<D||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var xd=!0;f.noInitialRun&&(xd=!1);wd();
