var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");m=l?ja.dirname(m)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ja.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!f.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=f);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ka||a.context instanceof ka))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});ca=(a,b)=>{process.exitCode=a;throw b;};f.inspect=()=>"[Emscripten Module object]"}else if(da||l)l?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):"",
fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var q=f.print||console.log.bind(console),t=f.printErr||console.error.bind(console);
Object.assign(f,aa);aa=null;f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var la;f.wasmBinary&&(la=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");var ma,y=!1,na,B,C,oa,pa,D,E,qa;
function ra(){var a=ma.buffer;f.HEAP8=B=new Int8Array(a);f.HEAP16=oa=new Int16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU8=C=new Uint8Array(a);f.HEAPU16=pa=new Uint16Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=qa=new Float32Array(a);f.HEAPF64=new Float64Array(a)}var sa,ta=[],ua=[],va=[],wa=[];function xa(){var a=f.preRun.shift();ta.unshift(a)}var F=0,ya=null,za=null;
function w(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";t(a);y=!0;na=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Aa(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="module.wasm";if(!Aa(G)){var Ba=G;G=f.locateFile?f.locateFile(Ba,m):m+Ba}function Ca(a){try{if(a==G&&la)return new Uint8Array(la);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function Da(a){if(!la&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ca(a));if(ha)return new Promise((b,c)=>{ha(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ca(a))}function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{t("failed to asynchronously prepare wasm: "+d);w(d)})}
function Fa(a,b){var c=G;la||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){t("wasm streaming compile failed: "+e);t("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ga(a){for(;0<a.length;)a.shift()(f)}var Ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function I(a,b){return a?H(C,a,b):""}
function Ia(a){this.Wa=a-24;this.ic=function(b){E[this.Wa+4>>2]=b};this.hc=function(b){E[this.Wa+8>>2]=b};this.Ta=function(b,c){this.fc();this.ic(b);this.hc(c)};this.fc=function(){E[this.Wa+16>>2]=0}}var Ja=0,Ka=0,La;La=ea?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function Ma(a){a instanceof ka||"unwind"==a||ca(1,a)}function Na(a){na=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);y=!0}ca(a,new ka(a))}
function Oa(a){if(!y)try{if(a(),!noExitRuntime)try{na=a=na,Na(a)}catch(b){Ma(b)}}catch(b){Ma(b)}}function Pa(a){setTimeout(()=>{Oa(a)},1E4)}var Qa=f.preloadPlugins||[],Ra=!1,J=null,K=0,Sa=null,Ta=0,Ua=0,Va=0,Wa=0,Xa=[],Ya={},Za,$a,ab,bb=!1,cb=!1,db=[];
function eb(){function a(){cb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!fb){fb=!0;Qa.push({canHandle:function(c){return!f.Rc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=new Blob([c],{type:gb(d)});k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:gb(d)}));var n=URL.createObjectURL(k),r=new Image;r.onload=()=>{r.complete||w("Image "+
d+" could not be decoded");var p=document.createElement("canvas");p.width=r.width;p.height=r.height;p.getContext("2d").drawImage(r,0,0);URL.revokeObjectURL(n);e&&e(c)};r.onerror=()=>{q("Image "+n+" could not be decoded");g&&g()};r.src=n}});Qa.push({canHandle:function(c){return!f.Qc&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){k||(k=!0,e&&e(c))}var k=!1,n=URL.createObjectURL(new Blob([c],{type:gb(d)})),r=new Audio;r.addEventListener("canplaythrough",()=>g(r),!1);
r.onerror=function(){if(!k){t("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var p="",u=0,v=0,A=0;A<c.length;A++)for(u=u<<8|c[A],v+=8;6<=v;){var h=u>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[h]}2==v?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],p+="=="):4==v&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],p+="=");r.src="data:audio/x-"+d.substr(-3)+
";base64,"+p;g(r)}};r.src=n;Pa(()=>{g(r)})}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!cb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function hb(a,b,c,d){if(b&&f.fb&&a==f.canvas)return f.fb;var e;if(b){var g={antialias:!1,alpha:!1,qc:2};if(d)for(var k in d)g[k]=d[k];if("undefined"!=typeof ib&&(e=jb(a,g)))var n=kb[e].kb}else n=a.getContext("2d");if(!n)return null;c&&(b||"undefined"==typeof L||w("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.fb=n,b&&(M=kb[e],f.fb=L=M&&M.kb),f.Uc=b,db.forEach(r=>r()),eb());return n}var lb=!1,mb=void 0,nb=void 0;
function ob(a,b){function c(){bb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=pb,mb&&d.requestPointerLock(),bb=!0,nb?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=E[SDL.screen>>2]|8388608),qb(f.canvas),rb()):qb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),nb?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=E[SDL.screen>>2]&
-8388609),qb(f.canvas),rb()):qb(d));if(f.onFullScreen)f.onFullScreen(bb);if(f.onFullscreen)f.onFullscreen(bb)}mb=a;nb=b;"undefined"==typeof mb&&(mb=!0);"undefined"==typeof nb&&(nb=!1);var d=f.canvas;lb||(lb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function pb(){if(!bb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var sb=0;function tb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===sb)sb=b+1E3/60;else for(;b+2>=sb;)sb+=1E3/60;setTimeout(a,Math.max(sb-b,0))}}
function gb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ub=0,vb=0,wb=0,xb=0;
function yb(a){if(cb)"mousemove"!=a.type&&"mozMovementX"in a?wb=xb=0:(wb=a.movementX||a.mozMovementX||a.webkitMovementX||0,xb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ub=SDL.Nc+wb,vb=SDL.Oc+xb):(ub+=wb,vb+=xb);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,wb=e-ub,xb=a-vb,ub=e,vb=a)}}var zb=[];function rb(){var a=f.canvas;zb.forEach(b=>b(a.width,a.height))}function Ab(a,b,c){qb(f.canvas,a,b);c||rb()}
function qb(a,b,c){b&&c?(a.Ac=b,a.oc=c):(b=a.Ac,c=a.oc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}nb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var fb;
function Bb(a,b){Ua=a;Va=b;if(Sa)if(Ra||(Ra=!0),0==a)J=function(){var d=Math.max(0,$a+b-La())|0;setTimeout(ab,d)};else if(1==a)J=function(){tb(ab)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);l?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}J=function(){setImmediate(ab)}}}
function Cb(a,b,c,d,e){!Sa||w("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Sa=a;Ta=d;var g=K;Ra=!1;ab=function(){if(!y)if(0<Xa.length){var k=Date.now(),n=Xa.shift();n.Jc(n.Dc);if(Za){var r=Za,p=0==r%1?r-1:Math.floor(r);Za=n.Gc?p:(8*r+(p+.5))/9}q('main loop blocker "'+n.name+'" took '+(Date.now()-k)+" ms");f.setStatus&&(k=f.statusMessage||"Please wait...",
n=Za,r=Ya.Ic,n?n<r?f.setStatus(k+" ("+(r-n)+"/"+r+")"):f.setStatus(k):f.setStatus(""));g<K||setTimeout(ab,0)}else if(!(g<K))if(Wa=Wa+1|0,1==Ua&&1<Va&&0!=Wa%Va)J();else{0==Ua&&($a=La());if(M)for(k=M.cb,M.cb=M.ib,M.ib=k,k=M.Xa,M.Xa=M.rb,M.rb=k,k=Db(2097152),n=0;n<=k;++n)M.Xa[n]=0;y||f.preMainLoop&&!1===f.preMainLoop()||(Oa(a),f.postMainLoop&&f.postMainLoop());g<K||("object"==typeof SDL&&SDL.audio&&SDL.audio.tc&&SDL.audio.tc(),J())}};e||(b&&0<b?Bb(0,1E3/b):Bb(1,1),J());if(c)throw"unwind";}
function N(a){return sa.get(a)}var Eb={};function Fb(){if(!Gb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Eb)void 0===Eb[b]?delete a[b]:a[b]=Eb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Gb=c}return Gb}var Gb,Hb=[null,[],[]],Ib=1,Jb=[],O=[],Kb=[],Lb=[],P=[],Mb=[],kb=[],Nb=[1,1,2,2,4,4,4,2,3,4,8];
function Q(a){Ob||(Ob=a)}function Pb(a){for(var b=Ib++,c=a.length;c<b;c++)a[c]=null;return b}function Db(a){return 32-Math.clz32(0===a?0:a-1)}
function Qb(a){Rb=!1;for(var b=0;b<M.Qb;++b){var c=M.eb[b];if(c.ub&&c.enabled){Rb=!0;var d=c.Db;d=0<d?a*d:c.size*Nb[c.type-5120]*a;var e=Db(d);var g=M.cb[e],k=M.Xa[e];M.Xa[e]=M.Xa[e]+1&63;var n=g[k];n?e=n:(n=L.getParameter(34964),g[k]=L.createBuffer(),L.bindBuffer(34962,g[k]),L.bufferData(34962,1<<e,35048),L.bindBuffer(34962,n),e=g[k]);L.bindBuffer(34962,e);L.bufferSubData(34962,0,C.subarray(c.Wa,c.Wa+d));c.cc.call(L,b,c.size,c.type,c.Vb,c.Db,0)}}}
function jb(a,b){a.Ta||(a.Ta=a.getContext,a.getContext=function(d,e){e=a.Ta(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Sb(c,b):0}
function Sb(a,b){var c=Pb(kb),d={Lc:c,attributes:b,version:b.qc,kb:a};a.canvas&&(a.canvas.Bc=d);kb[c]=d;("undefined"==typeof b.mc||b.mc)&&Tb(d);d.Qb=d.kb.getParameter(34921);d.eb=[];for(a=0;a<d.Qb;a++)d.eb[a]={enabled:!1,ub:!1,size:0,type:0,Vb:0,Db:0,Wa:0,cc:null};a=Db(2097152);d.Xa=[];d.rb=[];d.Xa.length=d.rb.length=a+1;d.cb=[];d.ib=[];d.cb.length=d.ib.length=a+1;d.bb=[];d.bb.length=a+1;for(b=0;b<=a;++b){d.bb[b]=null;d.Xa[b]=d.rb[b]=0;d.cb[b]=[];d.ib[b]=[];var e=d.cb[b],g=d.ib[b];e.length=g.length=
64;for(var k=0;64>k;++k)e[k]=g[k]=null}return c}
function Tb(a){a||(a=M);if(!a.pc){a.pc=!0;var b=a.kb;b.Hc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Mc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Jb=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Jb)b.Jb=b.getExtension("EXT_disjoint_timer_query");b.Pc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var ib={},Ob,M,Rb;function Ub(a,b,c,d){for(var e=0;e<a;e++){var g=L[c](),k=g&&Pb(d);g?(g.name=k,d[k]=g):Q(1282);D[b+4*e>>2]=k}}
function Vb(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}function Wb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Xb(a){a-=5120;return 0==a?B:1==a?C:2==a?oa:4==a?D:6==a?qa:5==a||28922==a||28520==a||30779==a||30782==a?E:pa}function Yb(a){var b=L.lc;if(b){var c=b.jb[a];"number"==typeof c&&(b.jb[a]=c=L.getUniformLocation(b,b.ac[a]+(0<c?"["+c+"]":"")));return c}Q(1282)}
function Zb(a,b,c,d){this.id=a;this.y=this.x=0;this.Ab=!1;this.$b=this.Zb=0;this.width=b;this.height=c;this.Yb=b;this.Xb=c;this.title=d;this.attributes=R;this.buttons=0;this.keys=[];this.yb=[];this.Hb=this.Pb=this.zb=this.Wb=this.lb=this.xb=this.Tb=this.dc=this.Nb=this.ec=this.title=null}function $b(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}function ac(a){var b=$b(a)+1,c=bc(b);c&&Vb(a,C,c,b);return c}
function cc(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ea)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}w("initRandomDevice")}function dc(a){return(dc=cc())(a)}
var ec=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},fc=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ec(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},gc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},hc=a=>
{if("/"===a)return"/";a=fc(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function ic(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ec(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function jc(a,b){var c=Array($b(a)+1);a=Vb(a,c,0,c.length);b&&(c.length=a);return c}var kc=[];
function lc(a,b){kc[a]={input:[],output:[],ab:b};mc(a,nc)}
var nc={open:function(a){var b=kc[a.node.rdev];if(!b)throw new S(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ab.fsync(a.tty)},fsync:function(a){a.tty.ab.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ab.Ob)throw new S(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.ab.Ob(a.tty)}catch(n){throw new S(29);}if(void 0===k&&0===e)throw new S(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ab.Bb)throw new S(60);
try{for(var e=0;e<d;e++)a.tty.ab.Bb(a.tty,b[c+e])}catch(g){throw new S(29);}d&&(a.node.timestamp=Date.now());return e}},oc={Ob:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=jc(b,!0)}return a.input.shift()},Bb:function(a,b){null===b||10===b?(q(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(q(H(a.output,0)),a.output=[])}},pc={Bb:function(a,b){null===b||10===b?(t(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(t(H(a.output,0)),a.output=[])}},T={Qa:null,Ua:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.Qa||(T.Qa={dir:{node:{Va:T.Na.Va,Ra:T.Na.Ra,lookup:T.Na.lookup,pb:T.Na.pb,rename:T.Na.rename,unlink:T.Na.unlink,rmdir:T.Na.rmdir,readdir:T.Na.readdir,symlink:T.Na.symlink},stream:{Ya:T.Oa.Ya}},file:{node:{Va:T.Na.Va,Ra:T.Na.Ra},stream:{Ya:T.Oa.Ya,read:T.Oa.read,write:T.Oa.write,Gb:T.Oa.Gb,Rb:T.Oa.Rb,Ub:T.Oa.Ub}},link:{node:{Va:T.Na.Va,Ra:T.Na.Ra,readlink:T.Na.readlink},stream:{}},Ib:{node:{Va:T.Na.Va,Ra:T.Na.Ra},stream:qc}});c=rc(a,b,
c,d);16384===(c.mode&61440)?(c.Na=T.Qa.dir.node,c.Oa=T.Qa.dir.stream,c.Ma={}):32768===(c.mode&61440)?(c.Na=T.Qa.file.node,c.Oa=T.Qa.file.stream,c.Pa=0,c.Ma=null):40960===(c.mode&61440)?(c.Na=T.Qa.link.node,c.Oa=T.Qa.link.stream):8192===(c.mode&61440)&&(c.Na=T.Qa.Ib.node,c.Oa=T.Qa.Ib.stream);c.timestamp=Date.now();a&&(a.Ma[b]=c,a.timestamp=c.timestamp);return c},Kc:function(a){return a.Ma?a.Ma.subarray?a.Ma.subarray(0,a.Pa):new Uint8Array(a.Ma):new Uint8Array(0)},Kb:function(a,b){var c=a.Ma?a.Ma.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ma,a.Ma=new Uint8Array(b),0<a.Pa&&a.Ma.set(c.subarray(0,a.Pa),0))},uc:function(a,b){if(a.Pa!=b)if(0==b)a.Ma=null,a.Pa=0;else{var c=a.Ma;a.Ma=new Uint8Array(b);c&&a.Ma.set(c.subarray(0,Math.min(b,a.Pa)));a.Pa=b}},Na:{Va:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Pa:40960===(a.mode&
61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.jc=4096;b.blocks=Math.ceil(b.size/b.jc);return b},Ra:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.uc(a,b.size)},lookup:function(){throw sc[44];},pb:function(a,b,c,d){return T.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tc(b,c)}catch(g){}if(d)for(var e in d.Ma)throw new S(55);
}delete a.parent.Ma[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ma[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ma[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=tc(a,b),d;for(d in c.Ma)throw new S(55);delete a.Ma[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ma)a.Ma.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new S(28);
return a.link}},Oa:{read:function(a,b,c,d,e){var g=a.node.Ma;if(e>=a.node.Pa)return 0;a=Math.min(a.node.Pa-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===B.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ma||a.Ma.subarray)){if(g)return a.Ma=b.subarray(c,c+d),a.Pa=d;if(0===a.Pa&&0===e)return a.Ma=b.slice(c,c+d),a.Pa=d;if(e+d<=a.Pa)return a.Ma.set(b.subarray(c,c+d),e),d}T.Kb(a,e+
d);if(a.Ma.subarray&&b.subarray)a.Ma.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Ma[e+g]=b[c+g];a.Pa=Math.max(a.Pa,e+d);return d},Ya:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Pa);if(0>b)throw new S(28);return b},Gb:function(a,b,c){T.Kb(a.node,b+c);a.node.Pa=Math.max(a.node.Pa,b+c)},Rb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.Ma;if(e&2||a.buffer!==B.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);c=!0;w();b=void 0;if(!b)throw new S(48);B.set(a,b)}else c=!1,b=a.byteOffset;return{Wa:b,Cc:c}},Ub:function(a,b,c,d){T.Oa.write(a,b,0,d,c,!1);return 0}}};function uc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var vc=null,wc={},xc=[],yc=1,zc=null,Ac=!0,S=null,sc={},V=(a,b={})=>{a=ic(a);if(!a)return{path:"",node:null};b=Object.assign({Mb:!0,Cb:0},b);if(8<b.Cb)throw new S(32);a=a.split("/").filter(k=>!!k);for(var c=vc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=tc(c,a[e]);d=fc(d+"/"+a[e]);c.qb&&(!g||g&&b.Mb)&&(c=c.qb.root);if(!g||b.Lb)for(g=0;40960===(c.mode&61440);)if(c=Bc(d),d=ic(gc(d),c),c=V(d,{Cb:b.Cb+1}).node,40<g++)throw new S(32);}return{path:d,node:c}},Cc=a=>{for(var b;;){if(a===
a.parent)return a=a.Ua.Sb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},Dc=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zc.length},tc=(a,b)=>{var c;if(c=(c=Ec(a,"x"))?c:a.Na.lookup?0:2)throw new S(c,a);for(c=zc[Dc(a.id,b)];c;c=c.sc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Na.lookup(a,b)},rc=(a,b,c,d)=>{a=new Fc(a,b,c,d);b=Dc(a.parent.id,a.name);a.sc=zc[b];return zc[b]=a},Gc=a=>{var b=["r","w","rw"][a&3];
a&512&&(b+="w");return b},Ec=(a,b)=>{if(Ac)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Hc=(a,b)=>{try{return tc(a,b),20}catch(c){}return Ec(a,"wx")},Ic=()=>{for(var a=0;4096>=a;a++)if(!xc[a])return a;throw new S(33);},Kc=a=>{Jc||(Jc=function(){this.Ta={}},Jc.prototype={},Object.defineProperties(Jc.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.Ta.flags},
set:function(c){this.Ta.flags=c}},position:{get:function(){return this.Ta.position},set:function(c){this.Ta.position=c}}}));a=Object.assign(new Jc,a);var b=Ic();a.fd=b;return xc[b]=a},qc={open:a=>{a.Oa=wc[a.node.rdev].Oa;a.Oa.open&&a.Oa.open(a)},Ya:()=>{throw new S(70);}},mc=(a,b)=>{wc[a]={Oa:b}},Lc=(a,b)=>{var c="/"===b,d=!b;if(c&&vc)throw new S(10);if(!c&&!d){var e=V(b,{Mb:!1});b=e.path;e=e.node;if(e.qb)throw new S(10);if(16384!==(e.mode&61440))throw new S(54);}b={type:a,Sc:{},Sb:b,rc:[]};a=a.Ua(b);
a.Ua=b;b.root=a;c?vc=a:e&&(e.qb=b,e.Ua&&e.Ua.rc.push(b))},W=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=hc(a);if(!a||"."===a||".."===a)throw new S(28);var e=Hc(d,a);if(e)throw new S(e);if(!d.Na.pb)throw new S(63);return d.Na.pb(d,a,b,c)},Mc=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},Nc=(a,b)=>{if(!ic(a))throw new S(44);var c=V(b,{parent:!0}).node;if(!c)throw new S(44);b=hc(b);var d=Hc(c,b);if(d)throw new S(d);if(!c.Na.symlink)throw new S(63);c.Na.symlink(c,b,a)},Bc=a=>{a=V(a).node;if(!a)throw new S(44);
if(!a.Na.readlink)throw new S(28);return ic(Cc(a.parent),a.Na.readlink(a))},Pc=(a,b,c)=>{if(""===a)throw new S(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=fc(a);try{e=V(a,{Lb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new S(20);}else e=W(a,c,0),d=!0;if(!e)throw new S(44);8192===(e.mode&
61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new S(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Gc(b)||b&512)?31:Ec(e,Gc(b)):44))throw new S(c);if(b&512&&!d){c=e;c="string"==typeof c?V(c,{Lb:!0}).node:c;if(!c.Na.Ra)throw new S(63);if(16384===(c.mode&61440))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(d=Ec(c,"w"))throw new S(d);c.Na.Ra(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Kc({node:e,path:Cc(e),flags:b,seekable:!0,position:0,Oa:e.Oa,
zc:[],error:!1});e.Oa.open&&e.Oa.open(e);!f.logReadFiles||b&1||(Oc||(Oc={}),a in Oc||(Oc[a]=1));return e},Qc=(a,b,c,d)=>{var e=void 0;if(0>c||0>e)throw new S(28);if(null===a.fd)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(16384===(a.node.mode&61440))throw new S(31);if(!a.Oa.write)throw new S(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new S(8);if(!a.seekable||!a.Oa.Ya)throw new S(70);a.position=a.Oa.Ya(a,0,2);a.zc=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S(70);
b=a.Oa.write(a,b,0,c,e,d);g||(a.position+=b)},Rc=()=>{S||(S=function(a,b){this.name="ErrnoError";this.node=b;this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(a=>{sc[a]=new S(a);sc[a].stack="<generic error, no stack>"}))},Sc,Tc=()=>{var a="/";a="string"==typeof a?a:Cc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=fc(a+"/"+c);try{W(a,16895,0)}catch(d){}}}},Wc=(a,b,c)=>{a=fc("/dev/"+a);var d=uc(!!b,!!c);Uc||(Uc=64);var e=Uc++<<8|0;
mc(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,k,n,r)=>{for(var p=0,u=0;u<r;u++){try{var v=b()}catch(A){throw new S(29);}if(void 0===v&&0===p)throw new S(6);if(null===v||void 0===v)break;p++;k[n+u]=v}p&&(g.node.timestamp=Date.now());return p},write:(g,k,n,r)=>{for(var p=0;p<r;p++)try{c(k[n+p])}catch(u){throw new S(29);}r&&(g.node.timestamp=Date.now());return p}});Mc(a,d,e)},Uc,Jc,Oc,X=null,Xc=null,Y=null,R=null,Yc={131073:0,131074:0,131075:1,131076:1,131077:1,
131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0};
function Zc(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function $c(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ad(a){X&&X.Hb&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||N(X.Hb)(X.id,a))}function bd(a,b){if(X){var c=Zc(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.yb[a]=b;X.Pb&&(d&&(b=2),N(X.Pb)(X.id,c,a,b,$c()))}}}
function cd(){dd()}function ed(){dd()}function fd(a){bd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function gd(a){bd(a.keyCode,0)}function hd(){if(X)for(var a=0;a<X.yb.length;++a)X.yb[a]&&bd(a,0)}function jd(a){X&&(yb(a),a.target==f.canvas&&X.xb&&X.xb&&N(X.xb)(X.id,ub,vb))}function kd(a){X&&a.target==f.canvas&&X.lb&&N(X.lb)(X.id,1)}function ld(a){X&&a.target==f.canvas&&X.lb&&N(X.lb)(X.id,0)}
function md(a,b){if(X&&(yb(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.Tb&&N(X.Tb)(X.id,c,b,$c())}}function nd(a){X&&md(a,1)}function od(a){X&&md(a,0)}
function pd(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(X&&X.Wb&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;N(X.Wb)(X.id,b,c);a.preventDefault()}}
var Z={},qd=[],rd=null;
function dd(){if(Wa!==rd||!Wa){qd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];rd=Wa;for(var a=0;a<qd.length;++a){var b=qd[a];if(b){Z[a]||(q("glfw joystick connected:",a),Z[a]={id:ac(b.id),Fc:b.buttons.length,Ec:b.axes.length,buttons:bc(b.buttons.length),axes:bc(4*b.axes.length)});for(var c=Z[a],d=0;d<b.buttons.length;++d)B[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)qa[c.axes+4*d>>2]=b.axes[d]}else Z[a]&&(q("glfw joystick disconnected",
a),sd(Z[a].id),sd(Z[a].buttons),sd(Z[a].axes),delete Z[a])}}}
function td(a){function b(n){var r="/.glfw_dropped_files/"+n.name.replace(/\//g,"_"),p=new FileReader;p.onloadend=v=>{if(2!=p.readyState)++g,q("failed to read dropped file: "+n.name+": "+p.error);else{var A=new Uint8Array(v.target.result);v={};v.flags=v.flags||577;var h=Pc(r,v.flags,v.mode);if("string"==typeof A){var x=new Uint8Array($b(A)+1);A=Vb(A,x,0,x.length);Qc(h,x,A,v.kc)}else if(ArrayBuffer.isView(A))Qc(h,A,A.byteLength,v.kc);else throw Error("Unsupported data type");if(null===h.fd)throw new S(8);
h.nc&&(h.nc=null);try{h.Oa.close&&h.Oa.close(h)}catch(z){throw z;}finally{xc[h.fd]=null}h.fd=null;if(++g===e){N(X.zb)(X.id,e,c);for(v=0;v<d.length;++v)sd(d[v]);sd(c)}}};p.readAsArrayBuffer(n);var u=ac(r);d.push(u);E[c+4*k>>2]=u}if(X&&X.zb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=bc(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Tc();for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}
function ud(a){if(X&&X.zb)return a.preventDefault(),!1}function vd(a){return 0===a%4&&(0!==a%100||0===a%400)}var wd=[31,29,31,30,31,30,31,31,30,31,30,31],xd=[31,28,31,30,31,30,31,31,30,31,30,31];
function yd(a,b,c,d){function e(h,x,z){for(h="number"==typeof h?h.toString():h||"";h.length<x;)h=z[0]+h;return h}function g(h,x){return e(h,x,"0")}function k(h,x){function z(Vc){return 0>Vc?-1:0<Vc?1:0}var U;0===(U=z(h.getFullYear()-x.getFullYear()))&&0===(U=z(h.getMonth()-x.getMonth()))&&(U=z(h.getDate()-x.getDate()));return U}function n(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function r(h){var x=h.Za;for(h=new Date((new Date(h.$a+1900,0,1)).getTime());0<x;){var z=h.getMonth(),U=(vd(h.getFullYear())?wd:xd)[z];if(x>U-h.getDate())x-=U-h.getDate()+1,h.setDate(1),11>z?h.setMonth(z+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+x);break}}z=new Date(h.getFullYear()+1,0,4);x=n(new Date(h.getFullYear(),
0,4));z=n(z);return 0>=k(x,h)?0>=k(z,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var p=D[d+40>>2];d={xc:D[d>>2],wc:D[d+4>>2],sb:D[d+8>>2],Eb:D[d+12>>2],tb:D[d+16>>2],$a:D[d+20>>2],Sa:D[d+24>>2],Za:D[d+28>>2],Tc:D[d+32>>2],vc:D[d+36>>2],yc:p?I(p):""};c=I(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in p)c=c.replace(new RegExp(u,"g"),p[u]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");p={"%a":function(h){return v[h.Sa].substring(0,3)},"%A":function(h){return v[h.Sa]},"%b":function(h){return A[h.tb].substring(0,3)},"%B":function(h){return A[h.tb]},
"%C":function(h){return g((h.$a+1900)/100|0,2)},"%d":function(h){return g(h.Eb,2)},"%e":function(h){return e(h.Eb,2," ")},"%g":function(h){return r(h).toString().substring(2)},"%G":function(h){return r(h)},"%H":function(h){return g(h.sb,2)},"%I":function(h){h=h.sb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){for(var x=0,z=0;z<=h.tb-1;x+=(vd(h.$a+1900)?wd:xd)[z++]);return g(h.Eb+x,3)},"%m":function(h){return g(h.tb+1,2)},"%M":function(h){return g(h.wc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=
h.sb&&12>h.sb?"AM":"PM"},"%S":function(h){return g(h.xc,2)},"%t":function(){return"\t"},"%u":function(h){return h.Sa||7},"%U":function(h){return g(Math.floor((h.Za+7-h.Sa)/7),2)},"%V":function(h){var x=Math.floor((h.Za+7-(h.Sa+6)%7)/7);2>=(h.Sa+371-h.Za-2)%7&&x++;if(x)53==x&&(z=(h.Sa+371-h.Za)%7,4==z||3==z&&vd(h.$a)||(x=1));else{x=52;var z=(h.Sa+7-h.Za-1)%7;(4==z||5==z&&vd(h.$a%400-1))&&x++}return g(x,2)},"%w":function(h){return h.Sa},"%W":function(h){return g(Math.floor((h.Za+7-(h.Sa+6)%7)/7),2)},
"%y":function(h){return(h.$a+1900).toString().substring(2)},"%Y":function(h){return h.$a+1900},"%z":function(h){h=h.vc;var x=0<=h;h=Math.abs(h)/60;return(x?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.yc},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(u in p)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),p[u](d)));c=c.replace(/\0\0/g,"%");u=jc(c,!1);if(u.length>b)return 0;B.set(u,a);return u.length-1}f.requestFullscreen=function(a,b){ob(a,b)};
f.requestAnimationFrame=function(a){tb(a)};f.setCanvasSize=function(a,b,c){Ab(a,b,c)};f.pauseMainLoop=function(){J=null;K++};f.resumeMainLoop=function(){K++;var a=Ua,b=Va,c=Sa;Sa=null;Cb(c,0,!1,Ta,!0);Bb(a,b);J()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return hb(a,b,c,d)};var L;
function Fc(a,b,c,d){a||(a=this);this.parent=a;this.Ua=a.Ua;this.qb=null;this.id=yc++;this.name=b;this.mode=c;this.Na={};this.Oa={};this.rdev=d}Object.defineProperties(Fc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Rc();zc=Array(4096);Lc(T,"/");W("/tmp",16895,0);W("/home",16895,0);W("/home/web_user",16895,0);
(()=>{W("/dev",16895,0);mc(259,{read:()=>0,write:(d,e,g,k)=>k});Mc("/dev/null",259);lc(1280,oc);lc(1536,pc);Mc("/dev/tty",1280);Mc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=dc(a).byteLength);return a[--b]};Wc("random",c);Wc("urandom",c);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();
(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);Lc({Ua:()=>{var b=rc(a,"fd",16895,73);b.Na={lookup:(c,d)=>{var e=xc[+d];if(!e)throw new S(8);c={parent:null,Ua:{Sb:"fake"},Na:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var zd={p:function(a,b,c,d){w(`Assertion failed: ${I(a)}, at: `+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},m:function(a,b,c){(new Ia(a)).Ta(b,c);Ja=a;Ka++;throw Ja;},L:function(){return!0},q:function(){w("")},O:La,P:function(a,b,c){C.copyWithin(a,b,b+c)},K:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var k=ma.buffer;try{ma.grow(g.call(e,2147483648,
d)-k.byteLength+65535>>>16);ra();var n=1;break a}catch(r){}n=void 0}if(n)return!0}return!1},W:function(a){eval(I(a))},X:function(a,b,c){a=N(a);Cb(a,b,c)},I:function(a,b){var c=0;Fb().forEach(function(d,e){var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)B[e++>>0]=d.charCodeAt(g);B[e>>0]=0;c+=d.length+1});return 0},J:function(a,b){var c=Fb();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},N:function(){return 52},G:function(){return 70},t:function(a,b,c,d){for(var e=
0,g=0;g<c;g++){var k=E[b>>2],n=E[b+4>>2];b+=8;for(var r=0;r<n;r++){var p=C[k+r],u=Hb[a];0===p||10===p?((1===a?q:t)(H(u,0)),u.length=0):u.push(p)}e+=n}E[d>>2]=e;return 0},s:function(a,b){L.attachShader(O[a],P[b])},b:function(a,b){34962==a?L.gb=b:34963==a&&(L.hb=b);35051==a?L.vb=b:35052==a&&(L.wb=b);L.bindBuffer(a,Jb[b])},n:function(a,b){L.bindFramebuffer(a,Kb[b])},ja:function(a,b){L.bindTexture(a,Lb[b])},Y:function(a){L.bindVertexArray(Mb[a]);a=L.getParameter(34965);L.hb=a?a.name|0:0},a:function(a,
b,c,d){c&&b?L.bufferData(a,C,d,c,b):L.bufferData(a,b,d)},ga:function(a){return L.checkFramebufferStatus(a)},Q:function(a){L.clear(a)},R:function(a,b,c,d){L.clearColor(a,b,c,d)},y:function(a){L.compileShader(P[a])},M:function(){var a=Pb(O),b=L.createProgram();b.name=a;b.ob=b.mb=b.nb=0;b.Fb=1;O[a]=b;return a},D:function(a){var b=Pb(P);P[b]=L.createShader(a);return b},i:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=Jb[d];e&&(L.deleteBuffer(e),e.name=0,Jb[d]=null,d==L.gb&&(L.gb=0),d==L.hb&&(L.hb=
0),d==L.vb&&(L.vb=0),d==L.wb&&(L.wb=0))}},ea:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],e=Kb[d];e&&(L.deleteFramebuffer(e),e.name=0,Kb[d]=null)}},C:function(a){if(a){var b=O[a];b?(L.deleteProgram(b),b.name=0,O[a]=null):Q(1281)}},k:function(a){if(a){var b=P[a];b?(L.deleteShader(b),P[a]=null):Q(1281)}},fa:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=Lb[d];e&&(L.deleteTexture(e),e.name=0,Lb[d]=null)}},S:function(a){L.depthFunc(a)},o:function(a,b){L.detachShader(O[a],P[b])},g:function(a){M.eb[a].enabled=
!1;L.disableVertexAttribArray(a)},da:function(a,b,c){Qb(b+c);L.drawArrays(a,b,c);Rb&&L.bindBuffer(34962,Jb[L.gb])},u:function(a,b,c,d){if(!L.hb){var e=1*Nb[c-5120]*b;var g=Db(e);var k=M.bb[g];k?g=k:(k=L.getParameter(34965),M.bb[g]=L.createBuffer(),L.bindBuffer(34963,M.bb[g]),L.bufferData(34963,1<<g,35048),L.bindBuffer(34963,k),g=M.bb[g]);L.bindBuffer(34963,g);L.bufferSubData(34963,0,C.subarray(d,d+e));d=0}Qb(b);L.drawElements(a,b,c,d);Rb&&L.bindBuffer(34962,Jb[L.gb]);L.hb||L.bindBuffer(34963,null)},
T:function(a){L.enable(a)},d:function(a){M.eb[a].enabled=!0;L.enableVertexAttribArray(a)},ha:function(a,b,c,d,e){L.framebufferTexture2D(a,b,c,Lb[d],e)},j:function(a,b){Ub(a,b,"createBuffer",Jb)},la:function(a,b){Ub(a,b,"createFramebuffer",Kb)},ka:function(a,b){Ub(a,b,"createTexture",Lb)},Z:function(a,b){Ub(a,b,"createVertexArray",Mb)},f:function(a,b){return L.getAttribLocation(O[a],I(b))},ma:function(a,b,c,d){a=L.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?Vb(a,C,d,b):0;c&&(D[c>>
2]=b)},E:function(a,b,c){if(c)if(a>=Ib)Q(1281);else if(a=O[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.ob)for(b=0;b<L.getProgramParameter(a,35718);++b)a.ob=Math.max(a.ob,L.getActiveUniform(a,b).name.length+1);D[c>>2]=a.ob}else if(35722==b){if(!a.mb)for(b=0;b<L.getProgramParameter(a,35721);++b)a.mb=Math.max(a.mb,L.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.mb}else if(35381==b){if(!a.nb)for(b=0;b<L.getProgramParameter(a,35382);++b)a.nb=
Math.max(a.nb,L.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.nb}else D[c>>2]=L.getProgramParameter(a,b);else Q(1281)},w:function(a,b,c,d){a=L.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?Vb(a,C,d,b):0;c&&(D[c>>2]=b)},x:function(a,b,c){c?35716==b?(a=L.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(P[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=L.getShaderParameter(P[a],b):Q(1281)},c:function(a,b){b=I(b);if(a=O[a]){var c=
a,d=c.jb,e=c.bc,g;if(!d)for(c.jb=d={},c.ac={},g=0;g<L.getProgramParameter(c,35718);++g){var k=L.getActiveUniform(c,g);var n=k.name;k=k.size;var r=Wb(n);r=0<r?n.slice(0,r):n;var p=c.Fb;c.Fb+=k;e[r]=[k,p];for(n=0;n<k;++n)d[p]=n,c.ac[p++]=r}c=a.jb;d=0;e=b;g=Wb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.bc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else Q(1281);return-1},F:function(a){a=O[a];L.linkProgram(a);a.jb=0;a.bc={}},ca:function(a,b,c,d,e,g,k){if(L.vb)L.readPixels(a,
b,c,d,e,g,k);else{var n=Xb(g);L.readPixels(a,b,c,d,e,g,n,k>>31-Math.clz32(n.BYTES_PER_ELEMENT))}},A:function(a,b,c,d){for(var e="",g=0;g<b;++g){var k=d?D[d+4*g>>2]:-1;e+=I(D[c+4*g>>2],0>k?void 0:k)}L.shaderSource(P[a],e)},ia:function(a,b,c,d,e,g,k,n,r){if(L.wb)L.texImage2D(a,b,c,d,e,g,k,n,r);else if(r){var p=Xb(n);L.texImage2D(a,b,c,d,e,g,k,n,p,r>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else L.texImage2D(a,b,c,d,e,g,k,n,null)},B:function(a,b,c){L.texParameteri(a,b,c)},h:function(a,b){L.uniform1f(Yb(a),
b)},v:function(a,b,c,d){b&&L.uniformMatrix4fv(Yb(a),!!c,qa,d>>2,16*b)},l:function(a){a=O[a];L.useProgram(a);L.lc=a},e:function(a,b,c,d,e,g){var k=M.eb[a];L.gb?(k.ub=!1,L.vertexAttribPointer(a,b,c,!!d,e,g)):(k.size=b,k.type=c,k.Vb=d,k.Db=e,k.Wa=g,k.ub=!0,k.cc=function(n,r,p,u,v,A){this.vertexAttribPointer(n,r,p,u,v,A)})},z:function(a,b,c,d){L.viewport(a,b,c,d)},aa:function(a,b,c,d){var e;for(e=0;e<Y.length&&null!==Y[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";
var g=e+1;if(0>=a||0>=b)g=0;else{d?ob():Ab(a,b);for(e=0;e<Y.length&&null==Y[e];e++);d=0<R[139265];e==Y.length&&(d?f.fb=hb(f.canvas,!0,!0,{antialias:1<R[135181],depth:0<R[135173],stencil:0<R[135174],alpha:0<R[135172]}):eb());!f.fb&&d?g=0:(a=new Zb(g,a,b,c),g-1==Y.length?Y.push(a):Y[g-1]=a,X=a,g=a.id)}return g},ba:function(){if(Y)return 1;La();R=Yc;Y=[];X=null;Xc="number"==typeof devicePixelRatio&&devicePixelRatio||1;window.addEventListener("gamepadconnected",cd,!0);window.addEventListener("gamepaddisconnected",
ed,!0);window.addEventListener("keydown",fd,!0);window.addEventListener("keypress",ad,!0);window.addEventListener("keyup",gd,!0);window.addEventListener("blur",hd,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Xc="number"==typeof devicePixelRatio&&devicePixelRatio||1;X&&X.dc&&N(X.dc)(X.id,Xc,Xc)})();f.canvas.addEventListener("touchmove",jd,!0);f.canvas.addEventListener("touchstart",nd,!0);f.canvas.addEventListener("touchcancel",
od,!0);f.canvas.addEventListener("touchend",od,!0);f.canvas.addEventListener("mousemove",jd,!0);f.canvas.addEventListener("mousedown",nd,!0);f.canvas.addEventListener("mouseup",od,!0);f.canvas.addEventListener("wheel",pd,!0);f.canvas.addEventListener("mousewheel",pd,!0);f.canvas.addEventListener("mouseenter",kd,!0);f.canvas.addEventListener("mouseleave",ld,!0);f.canvas.addEventListener("drop",td,!0);f.canvas.addEventListener("dragover",ud,!0);zb.push((b,c)=>{if(X){var d=!0;document.fullscreen||document.fullScreen||
document.mozFullScreen||document.webkitIsFullScreen?(X.Zb=X.x,X.$b=X.y,X.Yb=X.width,X.Xb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.Ab=!0):1==X.Ab?(X.x=X.Zb,X.y=X.$b,X.width=X.Yb,X.height=X.Xb,X.Ab=!1):X.width!=b||X.height!=c?(X.width=b,X.height=c):d=!1;d&&(Ab(X.width,X.height,!0),X&&X.ec&&N(X.ec)(X.id,X.width,X.height),X&&X.Nb&&N(X.Nb)(X.id,X.width,X.height))}});return 1},_:function(){},U:function(){},V:function(){},$:function(){window.removeEventListener("gamepadconnected",
cd,!0);window.removeEventListener("gamepaddisconnected",ed,!0);window.removeEventListener("keydown",fd,!0);window.removeEventListener("keypress",ad,!0);window.removeEventListener("keyup",gd,!0);window.removeEventListener("blur",hd,!0);f.canvas.removeEventListener("touchmove",jd,!0);f.canvas.removeEventListener("touchstart",nd,!0);f.canvas.removeEventListener("touchcancel",od,!0);f.canvas.removeEventListener("touchend",od,!0);f.canvas.removeEventListener("mousemove",jd,!0);f.canvas.removeEventListener("mousedown",
nd,!0);f.canvas.removeEventListener("mouseup",od,!0);f.canvas.removeEventListener("wheel",pd,!0);f.canvas.removeEventListener("mousewheel",pd,!0);f.canvas.removeEventListener("mouseenter",kd,!0);f.canvas.removeEventListener("mouseleave",ld,!0);f.canvas.removeEventListener("drop",td,!0);f.canvas.removeEventListener("dragover",ud,!0);f.canvas.width=f.canvas.height=1;X=Y=null},r:function(a,b){R[a]=b},H:function(a,b,c,d){return yd(a,b,c,d)}};
(function(){function a(c){c=c.exports;f.asm=c;ma=f.asm.na;ra();sa=f.asm.Ga;ua.unshift(f.asm.oa);F--;f.monitorRunDependencies&&f.monitorRunDependencies(F);if(0==F&&(null!==ya&&(clearInterval(ya),ya=null),za)){var d=za;za=null;d()}return c}var b={a:zd};F++;f.monitorRunDependencies&&f.monitorRunDependencies(F);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return t("Module.instantiateWasm callback failed with error: "+c),!1}Fa(b,function(c){a(c.instance)});return{}})();
f._updateShaderFunction=function(){return(f._updateShaderFunction=f.asm.pa).apply(null,arguments)};f._setRenderNeeded=function(){return(f._setRenderNeeded=f.asm.qa).apply(null,arguments)};f._translateState=function(){return(f._translateState=f.asm.ra).apply(null,arguments)};f._scaleState=function(){return(f._scaleState=f.asm.sa).apply(null,arguments)};f._resizeWindow=function(){return(f._resizeWindow=f.asm.ta).apply(null,arguments)};
f._resetState=function(){return(f._resetState=f.asm.ua).apply(null,arguments)};f._setScreenCenter=function(){return(f._setScreenCenter=f.asm.va).apply(null,arguments)};f._setMeshShowEdges=function(){return(f._setMeshShowEdges=f.asm.wa).apply(null,arguments)};f._setMeshSmoothShading=function(){return(f._setMeshSmoothShading=f.asm.xa).apply(null,arguments)};f._setMeshBothLeafs=function(){return(f._setMeshBothLeafs=f.asm.ya).apply(null,arguments)};
f._isModelEmpty=function(){return(f._isModelEmpty=f.asm.za).apply(null,arguments)};f._getFileSize=function(){return(f._getFileSize=f.asm.Aa).apply(null,arguments)};f._generateSTL=function(){return(f._generateSTL=f.asm.Ba).apply(null,arguments)};f._generatePLY=function(){return(f._generatePLY=f.asm.Ca).apply(null,arguments)};f._generateOBJ=function(){return(f._generateOBJ=f.asm.Da).apply(null,arguments)};f._generateGLB=function(){return(f._generateGLB=f.asm.Ea).apply(null,arguments)};
var Ad=f._main=function(){return(Ad=f._main=f.asm.Fa).apply(null,arguments)};function bc(){return(bc=f.asm.Ha).apply(null,arguments)}function sd(){return(sd=f.asm.Ia).apply(null,arguments)}function Bd(){return(Bd=f.asm.Ja).apply(null,arguments)}function Cd(){return(Cd=f.asm.Ka).apply(null,arguments)}function Dd(){return(Dd=f.asm.La).apply(null,arguments)}
f.ccall=function(a,b,c,d){var e={string:p=>{var u=0;if(null!==p&&void 0!==p&&0!==p){u=$b(p)+1;var v=Dd(u);Vb(p,C,v,u);u=v}return u},array:p=>{var u=Dd(p.length);B.set(p,u);return u}};a=f["_"+a];var g=[],k=0;if(d)for(var n=0;n<d.length;n++){var r=e[c[n]];r?(0===k&&(k=Bd()),g[n]=r(d[n])):g[n]=d[n]}c=a.apply(null,g);return c=function(p){0!==k&&Cd(k);return"string"===b?I(p):"boolean"===b?!!p:p}(c)};var Ed;za=function Fd(){Ed||Gd();Ed||(za=Fd)};
function Gd(){function a(){if(!Ed&&(Ed=!0,f.calledRun=!0,!y)){f.noFSInit||Sc||(Sc=!0,Rc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Wc("stdin",f.stdin):Nc("/dev/tty","/dev/stdin"),f.stdout?Wc("stdout",null,f.stdout):Nc("/dev/tty","/dev/stdout"),f.stderr?Wc("stderr",null,f.stderr):Nc("/dev/tty1","/dev/stderr"),Pc("/dev/stdin",0),Pc("/dev/stdout",1),Pc("/dev/stderr",1));Ac=!1;Ga(ua);Ga(va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Hd){var b=Ad;try{var c=b(0,0);na=c;Na(c)}catch(d){Ma(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),wa.unshift(b);Ga(wa)}}if(!(0<F)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)xa();Ga(ta);0<F||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Hd=!0;f.noInitialRun&&(Hd=!1);Gd();
