var f;f||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},f),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,k="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");m=k?ja.dirname(m)+"/":__dirname+"/";fa=(a,b)=>{a=ka(a)?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c,d=!0)=>{a=ka(a)?new URL(a):ja.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!f.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof la||a.context instanceof la))throw a;});ca=(a,b)=>{process.exitCode=a;throw b;}}else if(da||k)k?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src),m=m.startsWith("blob:")?"":m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1),fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var q=f.print||console.log.bind(console),t=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var ma;f.wasmBinary&&(ma=f.wasmBinary);"object"!=typeof WebAssembly&&na("no native wasm support detected");
var oa,x=!1,pa,y,A,qa,ra,B,D,sa;function ta(){var a=oa.buffer;f.HEAP8=y=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=sa=new Float32Array(a);f.HEAPF64=new Float64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var E=0,za=null,Aa=null;
function na(a){f.onAbort?.(a);a="Aborted("+a+")";t(a);x=!0;pa=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://"),Ca;Ca="module.wasm";if(!Ba(Ca)){var Da=Ca;Ca=f.locateFile?f.locateFile(Da,m):m+Da}function Ea(a){if(a==Ca&&ma)return new Uint8Array(ma);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}
function Fa(a){if(!ma&&(da||k)){if("function"==typeof fetch&&!ka(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ea(a));if(ha)return new Promise((b,c)=>{ha(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{t(`failed to asynchronously prepare wasm: ${d}`);na(d)})}
function Ha(a,b){var c=Ca;ma||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||ka(c)||ea||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){t(`wasm streaming compile failed: ${e}`);t("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}function la(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ia=a=>{for(;0<a.length;)a.shift()(f)},Ja=f.noExitRuntime||!0,Ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class La{constructor(a){this.mb=a-24}}var Ma=0,Na=0,Oa;Oa=()=>performance.now();var Pa=a=>{a instanceof la||"unwind"==a||ca(1,a)},Qa=a=>{pa=a;Ja||(f.onExit?.(a),x=!0);ca(a,new la(a))},Ra=()=>{if(!Ja)try{var a=pa;pa=a;Qa(a)}catch(b){Pa(b)}},Sa=a=>{setTimeout(()=>{if(!x)try{a(),Ra()}catch(b){Pa(b)}},1E4)},Ta=f.preloadPlugins||[],Ua=!1,G=null,Va=0,Wa=null,Xa=0,Ya=0,Za=0,$a=0,ab=[],bb={},cb,db,eb,H=!1,fb=!1,gb=[];
function hb(){function a(){fb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!ib){ib=!0;Ta.push({canHandle:function(c){return!f.Kc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var l=new Blob([c],{type:jb(d)});l.size!==c.length&&(l=new Blob([(new Uint8Array(c)).buffer],{type:jb(d)}));var p=URL.createObjectURL(l),r=new Image;r.onload=()=>{var n=document.createElement("canvas");
n.width=r.width;n.height=r.height;n.getContext("2d").drawImage(r,0,0);URL.revokeObjectURL(p);e?.(c)};r.onerror=()=>{t(`Image ${p} could not be decoded`);g?.()};r.src=p}});Ta.push({canHandle:function(c){return!f.Jc&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function g(){l||(l=!0,e?.(c))}var l=!1,p=URL.createObjectURL(new Blob([c],{type:jb(d)})),r=new Audio;r.addEventListener("canplaythrough",()=>g(r),!1);r.onerror=function(){if(!l){t(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var n="",u=0,w=0,C=0;C<c.length;C++)for(u=u<<8|c[C],w+=8;6<=w;){var h=u>>w-6&63;w-=6;n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[h]}2==w?(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],n+="=="):4==w&&(n+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],n+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+n;g(r)}};r.src=p;Sa(()=>{g(r)})}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
c=>{!fb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}function kb(a,b,c,d){if(b&&f.cb&&a==f.canvas)return f.cb;var e;if(b){var g={antialias:!1,alpha:!1,ec:2};if(d)for(var l in d)g[l]=d[l];if("undefined"!=typeof lb&&(e=mb(a,g)))var p=nb[e].pb}else p=a.getContext("2d");if(!p)return null;c&&(f.cb=p,b&&(ob=nb[e],f.cb=I=ob?.pb),f.Pc=b,gb.forEach(r=>r()),hb());return p}var pb=!1,J=void 0,K=void 0;
function qb(a,b){function c(){H=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=rb,J&&d.requestPointerLock(),H=!0,K?sb():L(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),K?tb():L(d));f.onFullScreen?.(H);f.onFullscreen?.(H)}J=a;K=b;"undefined"==typeof J&&(J=!0);"undefined"==typeof K&&(K=!1);var d=f.canvas;pb||(pb=!0,document.addEventListener("fullscreenchange",
c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):
null);e.requestFullscreen()}function rb(){if(!H)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var ub=0;function vb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ub)ub=b+1E3/60;else for(;b+2>=ub;)ub+=1E3/60;setTimeout(a,Math.max(ub-b,0))}}
function jb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var wb=0,xb=0,yb=0,zb=0;function Ab(a,b){var c=f.canvas.getBoundingClientRect(),d=f.canvas.height;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=f.canvas.width/c.width;b*=d/c.height;return{x:a,y:b}}
function Bb(a,b){const {x:c,y:d}=Ab(a,b);yb=c-wb;zb=d-xb;wb=c;xb=d}function Cb(a){fb?("mousemove"!=a.type&&"mozMovementX"in a?yb=zb=0:(yb=a.movementX||a.mozMovementX||a.webkitMovementX||0,zb=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(wb=SDL.Gc+yb,xb=SDL.Hc+zb):(wb+=yb,xb+=zb)):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.Oc,void 0!==a&&Ab(a.pageX,a.pageY)):Bb(a.pageX,a.pageY)}var Db=[];
function Eb(){var a=f.canvas;Db.forEach(b=>b(a.width,a.height))}function Fb(a,b,c){L(f.canvas,a,b);c||Eb()}function sb(){"undefined"!=typeof SDL&&(B[SDL.screen>>2]=D[SDL.screen>>2]|8388608);L(f.canvas);Eb()}function tb(){"undefined"!=typeof SDL&&(B[SDL.screen>>2]=D[SDL.screen>>2]&-8388609);L(f.canvas);Eb()}
function L(a,b,c){b&&c?(a.Eb=b,a.xb=c):(b=a.Eb,c=a.xb);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}K?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ib,Gb,Hb=(a,b)=>{Ya=a;Za=b;if(Wa)if(Ua||=!0,0==a)G=function(){var d=Math.max(0,db+b-Oa())|0;setTimeout(eb,d)};else if(1==a)G=function(){vb(eb)};else if(2==a){if("undefined"==typeof Gb)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Gb=function(d){c.push(d);k?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}else Gb=setImmediate;G=function(){Gb(eb)}}},Ib=(a,b,c,d,e)=>{Wa=a;Xa=d;var g=Va;Ua=!1;eb=function(){if(!x)if(0<ab.length){var l=ab.shift();l.Ac(l.pc);if(cb){var p=cb,r=0==p%1?p-1:Math.floor(p);cb=l.xc?r:(8*p+(r+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",p=cb,r=bb.zc,p?p<r?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g<Va||setTimeout(eb,0)}else if(!(g<Va))if($a=$a+1|0,1==Ya&&1<Za&&0!=$a%Za)G();else{0==Ya&&(db=Oa());if(!(x||f.preMainLoop&&
!1===f.preMainLoop())){if(!x)try{a(),Ra()}catch(n){Pa(n)}f.postMainLoop?.()}g<Va||("object"==typeof SDL&&SDL.audio?.Mc?.(),G())}};e||(b&&0<b?Hb(0,1E3/b):Hb(1,1),G());if(c)throw"unwind";},Jb=[],Kb,M=a=>{var b=Jb[a];b||(a>=Jb.length&&(Jb.length=a+1),Jb[a]=b=Kb.get(a));return b},Lb={},Nb=()=>{if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},
b;for(b in Lb)void 0===Lb[b]?delete a[b]:a[b]=Lb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Mb=c}return Mb},Mb,Ob=[null,[],[]],Pb=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Qb=1,Rb=[],N=[],Sb=[],Tb=[],O=[],Ub=[],nb=[],Vb=a=>{for(var b=Qb++,c=a.length;c<b;c++)a[c]=null;return b},Wb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=I[c](),l=g&&Vb(d);g?(g.name=l,d[l]=g):P||=1282;B[b+4*e>>2]=l}},mb=(a,b)=>{a.Ya||(a.Ya=a.getContext,a.getContext=function(d,e){e=a.Ya(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Xb(c,b):0},Xb=(a,b)=>{var c=Vb(nb),d={handle:c,attributes:b,
version:b.ec,pb:a};a.canvas&&(a.canvas.nc=d);nb[c]=d;("undefined"==typeof b.bc||b.bc)&&Yb(d);return c},Yb=a=>{a||=ob;if(!a.dc){a.dc=!0;var b=a.pb;b.yc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Fc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ib=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ib)b.Ib=b.getExtension("EXT_disjoint_timer_query");b.Ic=b.getExtension("WEBGL_multi_draw");Pb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},lb={},P,ob,Zb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e},$b=a=>"]"==a.slice(-1)&&
a.lastIndexOf("["),ac=a=>{a-=5120;return 0==a?y:1==a?A:2==a?qa:4==a?B:6==a?sa:5==a||28922==a||28520==a||30779==a||30782==a?D:ra},bc=a=>{var b=I.ac;if(b){var c=b.eb[a];"number"==typeof c&&(b.eb[a]=c=I.getUniformLocation(b,b.Vb[a]+(0<c?`[${c}]`:"")));return c}P||=1282};
function cc(a,b,c,d,e,g){this.id=a;this.y=this.x=0;this.gb=!1;this.Ub=this.Tb=0;this.width=b;this.height=c;this.wb=d;this.vb=e;this.Bb=b;this.Ab=c;this.title=g;this.attributes=Object.assign({},Q);this.buttons=0;this.keys=[];this.tb=[];this.title=null;this.Gb=this.Nb=this.ub=this.Sb=this.fb=this.sb=this.Qb=this.Xb=this.Lb=this.Yb=0}
var dc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},fc=a=>{var b=dc(a)+1,c=ec(b);c&&Zb(a,A,c,b);return c},gc=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ea)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}na("initRandomDevice")},hc=a=>(hc=gc())(a),ic=(a,
b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},jc=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ic(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},kc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},lc=a=>{if("/"===a)return"/";
a=jc(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},mc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=ic(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},nc=[];function oc(a,b){var c=Array(dc(a)+1);a=Zb(a,c,0,c.length);b&&(c.length=a);return c}var pc=[];
function qc(a,b){pc[a]={input:[],output:[],bb:b};rc(a,sc)}
var sc={open(a){var b=pc[a.node.rdev];if(!b)throw new R;a.tty=b;a.seekable=!1},close(a){a.tty.bb.fsync(a.tty)},fsync(a){a.tty.bb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.bb.Mb)throw new R;for(var e=0,g=0;g<d;g++){try{var l=a.tty.bb.Mb(a.tty)}catch(p){throw new R;}if(void 0===l&&0===e)throw new R;if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.bb.yb)throw new R;try{for(var e=0;e<d;e++)a.tty.bb.yb(a.tty,b[c+e])}catch(g){throw new R;
}d&&(a.node.timestamp=Date.now());return e}},tc={Mb(){a:{if(!nc.length){var a=null;if(ea){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}nc=oc(a,!0)}a=nc.shift()}return a},yb(a,
b){null===b||10===b?(q(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(q(F(a.output,0)),a.output=[])},Cc(){return{uc:25856,wc:5,tc:191,vc:35387,sc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Dc(){return 0},Ec(){return[24,80]}},uc={yb(a,b){null===b||10===b?(t(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(t(F(a.output,0)),a.output=[])}};
function vc(a,b){var c=a.Qa?a.Qa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Qa,a.Qa=new Uint8Array(b),0<a.Sa&&a.Qa.set(c.subarray(0,a.Sa),0))}
var S={Ta:null,Wa(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R;S.Ta||(S.Ta={dir:{node:{Xa:S.Pa.Xa,Ua:S.Pa.Ua,lookup:S.Pa.lookup,kb:S.Pa.kb,rename:S.Pa.rename,unlink:S.Pa.unlink,rmdir:S.Pa.rmdir,readdir:S.Pa.readdir,symlink:S.Pa.symlink},stream:{Za:S.Ra.Za}},file:{node:{Xa:S.Pa.Xa,Ua:S.Pa.Ua},stream:{Za:S.Ra.Za,read:S.Ra.read,write:S.Ra.write,Fb:S.Ra.Fb,Ob:S.Ra.Ob,Rb:S.Ra.Rb}},link:{node:{Xa:S.Pa.Xa,Ua:S.Pa.Ua,readlink:S.Pa.readlink},
stream:{}},Hb:{node:{Xa:S.Pa.Xa,Ua:S.Pa.Ua},stream:wc}});c=xc(a,b,c,d);16384===(c.mode&61440)?(c.Pa=S.Ta.dir.node,c.Ra=S.Ta.dir.stream,c.Qa={}):32768===(c.mode&61440)?(c.Pa=S.Ta.file.node,c.Ra=S.Ta.file.stream,c.Sa=0,c.Qa=null):40960===(c.mode&61440)?(c.Pa=S.Ta.link.node,c.Ra=S.Ta.link.stream):8192===(c.mode&61440)&&(c.Pa=S.Ta.Hb.node,c.Ra=S.Ta.Hb.stream);c.timestamp=Date.now();a&&(a.Qa[b]=c,a.timestamp=c.timestamp);return c},Bc(a){return a.Qa?a.Qa.subarray?a.Qa.subarray(0,a.Sa):new Uint8Array(a.Qa):
new Uint8Array(0)},Pa:{Xa(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Sa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Zb=4096;b.blocks=Math.ceil(b.size/b.Zb);return b},Ua(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==
b.size&&(b=b.size,a.Sa!=b))if(0==b)a.Qa=null,a.Sa=0;else{var c=a.Qa;a.Qa=new Uint8Array(b);c&&a.Qa.set(c.subarray(0,Math.min(b,a.Sa)));a.Sa=b}},lookup(){throw yc[44];},kb(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=zc(b,c)}catch(g){}if(d)for(var e in d.Qa)throw new R;}delete a.parent.Qa[a.name];a.parent.timestamp=Date.now();a.name=c;b.Qa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.Qa[b];a.timestamp=Date.now()},rmdir(a,b){var c=
zc(a,b),d;for(d in c.Qa)throw new R;delete a.Qa[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.Qa))b.push(c);return b},symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new R;return a.link}},Ra:{read(a,b,c,d,e){var g=a.node.Qa;if(e>=a.node.Sa)return 0;a=Math.min(a.node.Sa-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===y.buffer&&(g=
!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Qa||a.Qa.subarray)){if(g)return a.Qa=b.subarray(c,c+d),a.Sa=d;if(0===a.Sa&&0===e)return a.Qa=b.slice(c,c+d),a.Sa=d;if(e+d<=a.Sa)return a.Qa.set(b.subarray(c,c+d),e),d}vc(a,e+d);if(a.Qa.subarray&&b.subarray)a.Qa.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Qa[e+g]=b[c+g];a.Sa=Math.max(a.Sa,e+d);return d},Za(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Sa);if(0>b)throw new R;return b},Fb(a,b,c){vc(a.node,
b+c);a.node.Sa=Math.max(a.node.Sa,b+c)},Ob(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new R;a=a.node.Qa;if(e&2||a.buffer!==y.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;na();b=void 0;if(!b)throw new R;y.set(a,b)}else c=!1,b=a.byteOffset;return{mb:b,oc:c}},Rb(a,b,c,d){S.Ra.write(a,b,0,d,c,!1);return 0}}},Ac=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Bc=null,Cc={},Dc=[],Ec=1,Fc=null,Gc=!0,R=class{constructor(){this.name="ErrnoError"}},
yc={},Hc=class{constructor(){this.Ya={};this.node=null}get flags(){return this.Ya.flags}set flags(a){this.Ya.flags=a}get position(){return this.Ya.position}set position(a){this.Ya.position=a}},Ic=class{constructor(a,b,c,d){a||=this;this.parent=a;this.Wa=a.Wa;this.lb=null;this.id=Ec++;this.name=b;this.mode=c;this.Pa={};this.Ra={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}};function T(a,b={}){a=mc(a);if(!a)return{path:"",node:null};b=Object.assign({Kb:!0,zb:0},b);if(8<b.zb)throw new R;a=a.split("/").filter(l=>!!l);for(var c=Bc,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=zc(c,a[e]);d=jc(d+"/"+a[e]);c.lb&&(!g||g&&b.Kb)&&(c=c.lb.root);if(!g||b.Jb)for(g=0;40960===(c.mode&61440);)if(c=Jc(d),d=mc(kc(d),c),c=T(d,{zb:b.zb+1}).node,40<g++)throw new R;}return{path:d,node:c}}
function Kc(a){for(var b;;){if(a===a.parent)return a=a.Wa.Pb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Lc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Fc.length}function zc(a,b){var c=16384===(a.mode&61440)?(c=Mc(a,"x"))?c:a.Pa.lookup?0:2:54;if(c)throw new R;for(c=Fc[Lc(a.id,b)];c;c=c.hc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Pa.lookup(a,b)}
function xc(a,b,c,d){a=new Ic(a,b,c,d);b=Lc(a.parent.id,a.name);a.hc=Fc[b];return Fc[b]=a}function Nc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Mc(a,b){if(Gc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Oc(a,b){try{return zc(a,b),20}catch(c){}return Mc(a,"wx")}function Pc(a){a=Dc[a];if(!a)throw new R;return a}
var wc={open(a){a.Ra=Cc[a.node.rdev].Ra;a.Ra.open?.(a)},Za(){throw new R;}};function rc(a,b){Cc[a]={Ra:b}}function Qc(a,b){var c="/"===b;if(c&&Bc)throw new R;if(!c&&b){var d=T(b,{Kb:!1});b=d.path;d=d.node;if(d.lb)throw new R;if(16384!==(d.mode&61440))throw new R;}b={type:a,Lc:{},Pb:b,fc:[]};a=a.Wa(b);a.Wa=b;b.root=a;c?Bc=a:d&&(d.lb=b,d.Wa&&d.Wa.fc.push(b))}
function Rc(a,b,c){var d=T(a,{parent:!0}).node;a=lc(a);if(!a||"."===a||".."===a)throw new R;if(Oc(d,a))throw new R;if(!d.Pa.kb)throw new R;return d.Pa.kb(d,a,b,c)}function U(a){return Rc(a,16895,0)}function Sc(a,b,c){"undefined"==typeof c&&(c=b,b=438);Rc(a,b|8192,c)}function Tc(a,b){if(!mc(a))throw new R;var c=T(b,{parent:!0}).node;if(!c)throw new R;b=lc(b);if(Oc(c,b))throw new R;if(!c.Pa.symlink)throw new R;c.Pa.symlink(c,b,a)}
function Jc(a){a=T(a).node;if(!a)throw new R;if(!a.Pa.readlink)throw new R;return mc(Kc(a.parent),a.Pa.readlink(a))}
function Uc(a,b,c){if(""===a)throw new R;if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=jc(a);try{e=T(a,{Jb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new R;}else e=Rc(a,c,0),d=!0;if(!e)throw new R;8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new R;if(!d&&(e?40960===
(e.mode&61440)||16384===(e.mode&61440)&&("r"!==Nc(b)||b&512)||Mc(e,Nc(b)):1))throw new R;if(b&512&&!d){c=e;c="string"==typeof c?T(c,{Jb:!0}).node:c;if(!c.Pa.Ua)throw new R;if(16384===(c.mode&61440))throw new R;if(32768!==(c.mode&61440))throw new R;if(Mc(c,"w"))throw new R;c.Pa.Ua(c,{size:0,timestamp:Date.now()})}b&=-131713;e={node:e,path:Kc(e),flags:b,seekable:!0,position:0,Ra:e.Ra,mc:[],error:!1};c=-1;e=Object.assign(new Hc,e);if(-1==c)a:{for(c=0;4096>=c;c++)if(!Dc[c])break a;throw new R;}e.fd=c;
Dc[c]=e;e.Ra.open&&e.Ra.open(e);!f.logReadFiles||b&1||(Vc||={},a in Vc||(Vc[a]=1));return e}
function Wc(a,b,c,d){var e=void 0;if(0>c||0>e)throw new R;if(null===a.fd)throw new R;if(0===(a.flags&2097155))throw new R;if(16384===(a.node.mode&61440))throw new R;if(!a.Ra.write)throw new R;if(a.seekable&&a.flags&1024){if(null===a.fd)throw new R;if(!a.seekable||!a.Ra.Za)throw new R;a.position=a.Ra.Za(a,0,2);a.mc=[]}var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new R;b=a.Ra.write(a,b,0,c,e,d);g||(a.position+=b)}var Xc;
function Yc(){var a="/";a="string"==typeof a?a:Kc(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=jc(a+"/"+c);try{U(a)}catch(d){}}}}
function Zc(a,b,c){a=jc("/dev/"+a);var d=Ac(!!b,!!c);$c||=64;var e=$c++<<8|0;rc(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,l,p,r){for(var n=0,u=0;u<r;u++){try{var w=b()}catch(C){throw new R;}if(void 0===w&&0===n)throw new R;if(null===w||void 0===w)break;n++;l[p+u]=w}n&&(g.node.timestamp=Date.now());return n},write(g,l,p,r){for(var n=0;n<r;n++)try{c(l[p+n])}catch(u){throw new R;}r&&(g.node.timestamp=Date.now());return n}});Sc(a,d,e)}
var $c,Vc,V=null,ad=null,W=null,bd=null,Q=null,cd=null,dd={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},fd=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;
case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;
case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;
case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;
case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;
default:return-1}},gd=()=>{var a=V,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},hd=a=>{V&&V.Gb&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||M(V.Gb)(V.id,a))},jd=(a,b)=>{if(V){var c=fd(a);if(-1!=c){var d=b&&V.keys[c];V.keys[c]=b;V.tb[a]=b;V.Nb&&(d&&(b=2),M(V.Nb)(V.id,c,a,b,gd()))}}},ld=()=>{kd()},md=()=>{kd()},nd=a=>{jd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},od=a=>{jd(a.keyCode,0)},pd=()=>{if(V)for(var a=
0;a<V.tb.length;++a)V.tb[a]&&jd(a,0)},qd=a=>{if(V){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(cd===c.identifier){Bb(c.pageX,c.pageY);b=!0;break}if(!b)return}else Cb(a);a.target==f.canvas&&V.sb&&V.sb&&M(V.sb)(V.id,wb,xb)}},rd=a=>{V&&a.target==f.canvas&&V.fb&&M(V.fb)(V.id,1)},sd=a=>{V&&a.target==f.canvas&&V.fb&&M(V.fb)(V.id,0)},td=(a,b)=>{if(V&&a.target==f.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();
var d=!1;if(null===cd&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],cd=d.identifier,Bb(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(cd===e.identifier){cd=null;d=!0;break}if(!d)return}else Cb(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){V.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else V.buttons&=~(1<<c);V.Qb&&M(V.Qb)(V.id,c,b,gd())}},ud=a=>{V&&td(a,1)},vd=a=>{V&&td(a,0)},wd=a=>{switch(a.type){case "DOMMouseScroll":var b=
a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(V&&V.Sb&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;M(V.Sb)(V.id,b,c);a.preventDefault()}},xd=(a,b,c,d)=>{if(V){var e=!1;document.fullscreen||
document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?V.gb||(e=a!=screen.width||b!=screen.height,V.Tb=V.x,V.Ub=V.y,V.Bb=V.width,V.Ab=V.height,V.x=V.y=0,V.width=screen.width,V.height=screen.height,V.gb=!0):1==V.gb&&(e=a!=V.Bb||b!=V.Ab,V.x=V.Tb,V.y=V.Ub,V.width=V.Bb,V.height=V.Ab,V.gb=!1);if(e)Fb(V.width,V.height);else if(V.width!=a||V.height!=b||V.wb!=c||V.vb!=d)V.width=a,V.height=b,V.wb=c,V.vb=d,V&&V.Yb&&M(V.Yb)(V.id,V.width,V.height),V&&V.Lb&&M(V.Lb)(V.id,V.wb,V.vb)}},Y={},yd=
[],zd=null,kd=()=>{if($a!==zd||!$a){yd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];zd=$a;for(var a=0;a<yd.length;++a){var b=yd[a];if(b){Y[a]||(q("glfw joystick connected:",a),Y[a]={id:fc(b.id),rc:b.buttons.length,qc:b.axes.length,buttons:ec(b.buttons.length),axes:ec(4*b.axes.length)});for(var c=Y[a],d=0;d<b.buttons.length;++d)y[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)sa[c.axes+4*d>>2]=b.axes[d]}else Y[a]&&(q("glfw joystick disconnected",a),Ad(Y[a].id),
Ad(Y[a].buttons),Ad(Y[a].axes),delete Y[a])}}},Bd=a=>{function b(p){var r="/.glfw_dropped_files/"+p.name.replace(/\//g,"_"),n=new FileReader;n.onloadend=w=>{if(2!=n.readyState)++g,q("failed to read dropped file: "+p.name+": "+n.error);else{var C=new Uint8Array(w.target.result);w={};w.flags=w.flags||577;var h=Uc(r,w.flags,w.mode);if("string"==typeof C){var v=new Uint8Array(dc(C)+1);C=Zb(C,v,0,v.length);Wc(h,v,C,w.$b)}else if(ArrayBuffer.isView(C))Wc(h,C,C.byteLength,w.$b);else throw Error("Unsupported data type");
if(null===h.fd)throw new R;h.cc&&(h.cc=null);try{h.Ra.close&&h.Ra.close(h)}catch(z){throw z;}finally{Dc[h.fd]=null}h.fd=null;if(++g===e){M(V.ub)(V.id,e,c);for(w=0;w<d.length;++w)Ad(d[w]);Ad(c)}}};n.readAsArrayBuffer(p);var u=fc(r);d.push(u);D[c+4*l>>2]=u}if(V&&V.ub&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=ec(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,g=0;Yc();for(var l=0;l<e;++l)b(a.dataTransfer.files[l]);return!1}},Cd=
a=>{if(V&&V.ub)return a.preventDefault(),!1};
function Dd(a,b){function c(){H=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=rb,J&&d.requestPointerLock(),H=!0,K?sb():(L(d),Eb())):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),K?tb():(L(d),Eb()));if(f.onFullScreen)f.onFullScreen(H);if(f.onFullscreen)f.onFullscreen(H)}J=a;K=b;"undefined"==typeof J&&(J=!0);"undefined"==typeof K&&
(K=!1);var d=f.canvas;pb||(pb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Ed(a,b,c){var d=V&&0<V.attributes[139276]?ad:1;b&&c?(a.Eb=b,a.xb=c):(b=a.Eb,c=a.xb);var e=b,g=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(e/g<f.forcedAspectRatio?e=Math.round(g*f.forcedAspectRatio):g=Math.round(e/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var l=Math.min(screen.width/e,screen.height/
g);e=Math.round(e*l);g=Math.round(g*l)}K&&(b=e,c=g);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}
function Fd(a,b){var c=f.canvas.getBoundingClientRect(),d=f.canvas.clientHeight;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=f.canvas.clientWidth/c.width;b*=d/c.height;return{x:a,y:b}}function Gd(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}function Hd(){const a=f.canvas;L(a,a.clientWidth,a.clientHeight);Eb()}
function Id(){ad=Gd();V&&V.Xb&&M(V.Xb)(V.id,ad,ad);Hd()}
var Jd=a=>0===a%4&&(0!==a%100||0===a%400),Kd=[31,29,31,30,31,30,31,31,30,31,30,31],Ld=[31,28,31,30,31,30,31,31,30,31,30,31],Md=(a,b,c,d)=>{function e(h,v,z){for(h="number"==typeof h?h.toString():h||"";h.length<v;)h=z[0]+h;return h}function g(h,v){return e(h,v,"0")}function l(h,v){function z(ed){return 0>ed?-1:0<ed?1:0}var X;0===(X=z(h.getFullYear()-v.getFullYear()))&&0===(X=z(h.getMonth()-v.getMonth()))&&(X=z(h.getDate()-v.getDate()));return X}function p(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-
1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function r(h){var v=h.$a;for(h=new Date((new Date(h.ab+1900,0,1)).getTime());0<v;){var z=h.getMonth(),X=(Jd(h.getFullYear())?Kd:Ld)[z];if(v>X-h.getDate())v-=X-h.getDate()+1,h.setDate(1),11>z?h.setMonth(z+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+
1));else{h.setDate(h.getDate()+v);break}}z=new Date(h.getFullYear()+1,0,4);v=p(new Date(h.getFullYear(),0,4));z=p(z);return 0>=l(v,h)?0>=l(z,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=D[d+40>>2];d={kc:B[d>>2],jc:B[d+4>>2],nb:B[d+8>>2],Cb:B[d+12>>2],ob:B[d+16>>2],ab:B[d+20>>2],Va:B[d+24>>2],$a:B[d+28>>2],Nc:B[d+32>>2],ic:B[d+36>>2],lc:n?n?F(A,n):"":""};c=c?F(A,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in n)c=c.replace(new RegExp(u,"g"),n[u]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),C="January February March April May June July August September October November December".split(" ");n={"%a":h=>w[h.Va].substring(0,
3),"%A":h=>w[h.Va],"%b":h=>C[h.ob].substring(0,3),"%B":h=>C[h.ob],"%C":h=>g((h.ab+1900)/100|0,2),"%d":h=>g(h.Cb,2),"%e":h=>e(h.Cb,2," "),"%g":h=>r(h).toString().substring(2),"%G":r,"%H":h=>g(h.nb,2),"%I":h=>{h=h.nb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":h=>{for(var v=0,z=0;z<=h.ob-1;v+=(Jd(h.ab+1900)?Kd:Ld)[z++]);return g(h.Cb+v,3)},"%m":h=>g(h.ob+1,2),"%M":h=>g(h.jc,2),"%n":()=>"\n","%p":h=>0<=h.nb&&12>h.nb?"AM":"PM","%S":h=>g(h.kc,2),"%t":()=>"\t","%u":h=>h.Va||7,"%U":h=>g(Math.floor((h.$a+
7-h.Va)/7),2),"%V":h=>{var v=Math.floor((h.$a+7-(h.Va+6)%7)/7);2>=(h.Va+371-h.$a-2)%7&&v++;if(v)53==v&&(z=(h.Va+371-h.$a)%7,4==z||3==z&&Jd(h.ab)||(v=1));else{v=52;var z=(h.Va+7-h.$a-1)%7;(4==z||5==z&&Jd(h.ab%400-1))&&v++}return g(v,2)},"%w":h=>h.Va,"%W":h=>g(Math.floor((h.$a+7-(h.Va+6)%7)/7),2),"%y":h=>(h.ab+1900).toString().substring(2),"%Y":h=>h.ab+1900,"%z":h=>{h=h.ic;var v=0<=h;h=Math.abs(h)/60;return(v?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.lc,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(u in n)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),n[u](d)));c=c.replace(/\0\0/g,"%");u=oc(c,!1);if(u.length>b)return 0;y.set(u,a);return u.length-1};f.requestFullscreen=qb;f.requestAnimationFrame=vb;f.setCanvasSize=Fb;f.pauseMainLoop=function(){G=null;Va++};f.resumeMainLoop=function(){Va++;var a=Ya,b=Za,c=Wa;Wa=null;Ib(c,0,!1,Xa,!0);Hb(a,b);G()};f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
f.createContext=kb;var I;[44].forEach(a=>{yc[a]=new R;yc[a].stack="<generic error, no stack>"});Fc=Array(4096);Qc(S,"/");U("/tmp");U("/home");U("/home/web_user");(function(){U("/dev");rc(259,{read:()=>0,write:(d,e,g,l)=>l});Sc("/dev/null",259);qc(1280,tc);qc(1536,uc);Sc("/dev/tty",1280);Sc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=hc(a).byteLength);return a[--b]};Zc("random",c);Zc("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");Qc({Wa(){var b=xc(a,"fd",16895,73);b.Pa={lookup(c,d){var e=Pc(+d);c={parent:null,Wa:{Pb:"fake"},Pa:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Nd={a:(a,b,c,d)=>{na(`Assertion failed: ${a?F(A,a):""}, at: `+[b?b?F(A,b):"":"unknown filename",c,d?d?F(A,d):"":"unknown function"])},m:(a,b,c)=>{var d=new La(a);D[d.mb+16>>2]=0;D[d.mb+4>>2]=b;D[d.mb+8>>2]=c;Ma=a;Na++;throw Ma;},T:()=>1,r:()=>{na("")},V:Oa,W:(a,b,c)=>A.copyWithin(a,b,b+c),S:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-oa.buffer.byteLength+
65535)/65536;try{oa.grow(e);ta();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},ca:a=>{eval(a?F(A,a):"")},da:(a,b,c)=>{a=M(a);Ib(a,b,c)},Q:(a,b)=>{var c=0;Nb().forEach((d,e)=>{var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<d.length;++g)y[e++]=d.charCodeAt(g);y[e]=0;c+=d.length+1});return 0},R:(a,b)=>{var c=Nb();D[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);D[b>>2]=d;return 0},U:()=>52,O:function(){return 70},u:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var l=D[b>>2],p=D[b+4>>2];b+=8;for(var r=0;r<
p;r++){var n=A[l+r],u=Ob[a];0===n||10===n?((1===a?q:t)(F(u,0)),u.length=0):u.push(n)}e+=p}D[d>>2]=e;return 0},v:(a,b)=>{I.attachShader(N[a],O[b])},d:(a,b)=>{35051==a?I.qb=b:35052==a&&(I.rb=b);I.bindBuffer(a,Rb[b])},l:(a,b)=>{I.bindFramebuffer(a,Sb[b])},F:(a,b)=>{I.bindTexture(a,Tb[b])},ea:a=>{I.bindVertexArray(Ub[a])},c:(a,b,c,d)=>{c&&b?I.bufferData(a,A,d,c,b):I.bufferData(a,b,d)},B:a=>I.checkFramebufferStatus(a),X:a=>I.clear(a),Y:(a,b,c,d)=>I.clearColor(a,b,c,d),C:a=>{I.compileShader(O[a])},_:()=>
{var a=Vb(N),b=I.createProgram();b.name=a;b.jb=b.hb=b.ib=0;b.Db=1;N[a]=b;return a},K:a=>{var b=Vb(O);O[b]=I.createShader(a);return b},k:(a,b)=>{for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Rb[d];e&&(I.deleteBuffer(e),e.name=0,Rb[d]=null,d==I.qb&&(I.qb=0),d==I.rb&&(I.rb=0))}},ma:(a,b)=>{for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Sb[d];e&&(I.deleteFramebuffer(e),e.name=0,Sb[d]=null)}},I:a=>{if(a){var b=N[a];b?(I.deleteProgram(b),b.name=0,N[a]=null):P||=1281}},n:a=>{if(a){var b=O[a];b?(I.deleteShader(b),O[a]=
null):P||=1281}},na:(a,b)=>{for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Tb[d];e&&(I.deleteTexture(e),e.name=0,Tb[d]=null)}},Z:a=>I.depthFunc(a),q:(a,b)=>{I.detachShader(N[a],O[b])},t:a=>I.disable(a),j:a=>{I.disableVertexAttribArray(a)},la:(a,b,c)=>{I.drawArrays(a,b,c)},w:(a,b,c,d)=>{I.drawElements(a,b,c,d)},$:a=>I.enable(a),f:a=>{I.enableVertexAttribArray(a)},D:(a,b,c,d,e)=>{I.framebufferTexture2D(a,b,c,Tb[d],e)},b:(a,b)=>{Wb(a,b,"createBuffer",Rb)},H:(a,b)=>{Wb(a,b,"createFramebuffer",Sb)},G:(a,b)=>
{Wb(a,b,"createTexture",Tb)},fa:(a,b)=>{Wb(a,b,"createVertexArray",Ub)},h:(a,b)=>I.getAttribLocation(N[a],b?F(A,b):""),L:(a,b,c,d)=>{a=I.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?Zb(a,A,d,b):0;c&&(B[c>>2]=b)},M:(a,b,c)=>{if(c)if(a>=Qb)P||=1281;else if(a=N[a],35716==b)a=I.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.jb)for(b=0;b<I.getProgramParameter(a,35718);++b)a.jb=Math.max(a.jb,I.getActiveUniform(a,b).name.length+1);B[c>>
2]=a.jb}else if(35722==b){if(!a.hb)for(b=0;b<I.getProgramParameter(a,35721);++b)a.hb=Math.max(a.hb,I.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.hb}else if(35381==b){if(!a.ib)for(b=0;b<I.getProgramParameter(a,35382);++b)a.ib=Math.max(a.ib,I.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.ib}else B[c>>2]=I.getProgramParameter(a,b);else P||=1281},y:(a,b,c,d)=>{a=I.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?Zb(a,A,d,b):0;c&&(B[c>>2]=b)},z:(a,b,c)=>{c?35716==b?(a=I.getShaderInfoLog(O[a]),
null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=I.getShaderSource(O[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=I.getShaderParameter(O[a],b):P||=1281},e:(a,b)=>{b=b?F(A,b):"";if(a=N[a]){var c=a,d=c.eb,e=c.Wb,g;if(!d)for(c.eb=d={},c.Vb={},g=0;g<I.getProgramParameter(c,35718);++g){var l=I.getActiveUniform(c,g);var p=l.name;l=l.size;var r=$b(p);r=0<r?p.slice(0,r):p;var n=c.Db;c.Db+=l;e[r]=[l,n];for(p=0;p<l;++p)d[n]=p,c.Vb[n++]=r}c=a.eb;d=0;e=b;g=$b(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=
b.slice(0,g));if((e=a.Wb[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||I.getUniformLocation(a,b)))return d}else P||=1281;return-1},N:a=>{a=N[a];I.linkProgram(a);a.eb=0;a.Wb={}},ka:(a,b,c,d,e,g,l)=>{if(I.qb)I.readPixels(a,b,c,d,e,g,l);else{var p=ac(g);l>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);I.readPixels(a,b,c,d,e,g,p,l)}},J:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var l=(l=D[c+4*g>>2])?F(A,l,d?D[d+4*g>>2]:void 0):"";e+=l}I.shaderSource(O[a],e)},E:(a,b,c,d,e,g,l,p,r)=>{if(I.rb)I.texImage2D(a,b,c,d,e,g,l,p,r);else if(r){var n=
ac(p);I.texImage2D(a,b,c,d,e,g,l,p,n,r>>>31-Math.clz32(n.BYTES_PER_ELEMENT))}else I.texImage2D(a,b,c,d,e,g,l,p,null)},p:(a,b,c)=>I.texParameteri(a,b,c),i:(a,b)=>{I.uniform1f(bc(a),b)},x:(a,b,c,d)=>{b&&I.uniformMatrix4fv(bc(a),!!c,sa,d>>2,16*b)},o:a=>{a=N[a];I.useProgram(a);I.ac=a},g:(a,b,c,d,e,g)=>{I.vertexAttribPointer(a,b,c,!!d,e,g)},A:(a,b,c,d)=>I.viewport(a,b,c,d),ia:(a,b,c,d)=>{var e;for(e=0;e<W.length&&null!==W[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";
var g=e+1;if(0>=a||0>=b)g=0;else{d?qb():Fb(a,b);for(e=0;e<W.length&&null==W[e];e++);a=0<Q[139265];e==W.length&&(a?f.cb=kb(f.canvas,!0,!0,{antialias:1<Q[135181],depth:0<Q[135173],stencil:0<Q[135174],alpha:0<Q[135172]}):hb());!f.cb&&a?g=0:(e=f.canvas,c=new cc(g,e.clientWidth,e.clientHeight,e.width,e.height,c),g-1==W.length?W.push(c):W[g-1]=c,V=c,Hd(),g=c.id)}return g},ja:()=>{if(W)return 1;Oa();Q=Object.assign({},dd);W=[];V=null;ad=Gd();window.addEventListener("gamepadconnected",ld,!0);window.addEventListener("gamepaddisconnected",
md,!0);window.addEventListener("keydown",nd,!0);window.addEventListener("keypress",hd,!0);window.addEventListener("keyup",od,!0);window.addEventListener("blur",pd,!0);bd=window.matchMedia("(resolution: "+Gd()+"dppx)");bd.addEventListener("change",Id);f.canvas.addEventListener("touchmove",qd,!0);f.canvas.addEventListener("touchstart",ud,!0);f.canvas.addEventListener("touchcancel",vd,!0);f.canvas.addEventListener("touchend",vd,!0);f.canvas.addEventListener("mousemove",qd,!0);f.canvas.addEventListener("mousedown",
ud,!0);f.canvas.addEventListener("mouseup",vd,!0);f.canvas.addEventListener("wheel",wd,!0);f.canvas.addEventListener("mousewheel",wd,!0);f.canvas.addEventListener("mouseenter",rd,!0);f.canvas.addEventListener("mouseleave",sd,!0);f.canvas.addEventListener("drop",Bd,!0);f.canvas.addEventListener("dragover",Cd,!0);qb=Dd;Ab=Fd;L=Ed;Db.push((a,b)=>{if(V&&0<V.attributes[139276]){var c=f.canvas;xd(c.clientWidth,c.clientHeight,a,b)}else xd(a,b,a,b)});return 1},ga:()=>{},aa:()=>{},ba:()=>{},ha:()=>{window.removeEventListener("gamepadconnected",
ld,!0);window.removeEventListener("gamepaddisconnected",md,!0);window.removeEventListener("keydown",nd,!0);window.removeEventListener("keypress",hd,!0);window.removeEventListener("keyup",od,!0);window.removeEventListener("blur",pd,!0);f.canvas.removeEventListener("touchmove",qd,!0);f.canvas.removeEventListener("touchstart",ud,!0);f.canvas.removeEventListener("touchcancel",vd,!0);f.canvas.removeEventListener("touchend",vd,!0);f.canvas.removeEventListener("mousemove",qd,!0);f.canvas.removeEventListener("mousedown",
ud,!0);f.canvas.removeEventListener("mouseup",vd,!0);f.canvas.removeEventListener("wheel",wd,!0);f.canvas.removeEventListener("mousewheel",wd,!0);f.canvas.removeEventListener("mouseenter",rd,!0);f.canvas.removeEventListener("mouseleave",sd,!0);f.canvas.removeEventListener("drop",Bd,!0);f.canvas.removeEventListener("dragover",Cd,!0);bd&&bd.removeEventListener("change",Id);f.canvas.width=f.canvas.height=1;V=W=null},s:(a,b)=>{Q[a]=b},P:(a,b,c,d)=>Md(a,b,c,d)},Z=function(){function a(c){Z=c.exports;oa=
Z.oa;ta();Kb=Z.Ja;va.unshift(Z.pa);E--;f.monitorRunDependencies?.(E);0==E&&(null!==za&&(clearInterval(za),za=null),Aa&&(c=Aa,Aa=null,c()));return Z}var b={a:Nd};E++;f.monitorRunDependencies?.(E);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return t(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ha(b,function(c){a(c.instance)});return{}}();f._setMeshgenParams=(a,b,c)=>(f._setMeshgenParams=Z.qa)(a,b,c);f._updateShaderFunction=a=>(f._updateShaderFunction=Z.ra)(a);
f._regenerateMesh=()=>(f._regenerateMesh=Z.sa)();f._decimateMesh=(a,b)=>(f._decimateMesh=Z.ta)(a,b);f._setRenderNeeded=a=>(f._setRenderNeeded=Z.ua)(a);f._translateState=(a,b)=>(f._translateState=Z.va)(a,b);f._scaleState=(a,b,c)=>(f._scaleState=Z.wa)(a,b,c);f._resizeWindow=(a,b)=>(f._resizeWindow=Z.xa)(a,b);f._resetState=()=>(f._resetState=Z.ya)();f._setScreenCenter=(a,b)=>(f._setScreenCenter=Z.za)(a,b);f._setMeshShowEdges=a=>(f._setMeshShowEdges=Z.Aa)(a);
f._setMeshSmoothShading=a=>(f._setMeshSmoothShading=Z.Ba)(a);f._isModelEmpty=()=>(f._isModelEmpty=Z.Ca)();f._getFileSize=()=>(f._getFileSize=Z.Da)();f._generateSTL=()=>(f._generateSTL=Z.Ea)();f._generatePLY=()=>(f._generatePLY=Z.Fa)();f._generateOBJ=()=>(f._generateOBJ=Z.Ga)();f._generateGLB=()=>(f._generateGLB=Z.Ha)();var Od=f._main=(a,b)=>(Od=f._main=Z.Ia)(a,b),ec=a=>(ec=Z.Ka)(a),Ad=a=>(Ad=Z.La)(a),Pd=()=>(Pd=Z.Ma)(),Qd=a=>(Qd=Z.Na)(a),Rd=a=>(Rd=Z.Oa)(a);
f.ccall=(a,b,c,d)=>{var e={string:n=>{var u=0;if(null!==n&&void 0!==n&&0!==n){u=dc(n)+1;var w=Rd(u);Zb(n,A,w,u);u=w}return u},array:n=>{var u=Rd(n.length);y.set(n,u);return u}};a=f["_"+a];var g=[],l=0;if(d)for(var p=0;p<d.length;p++){var r=e[c[p]];r?(0===l&&(l=Pd()),g[p]=r(d[p])):g[p]=d[p]}c=a(...g);return c=function(n){0!==l&&Qd(l);return"string"===b?n?F(A,n):"":"boolean"===b?!!n:n}(c)};var Sd;Aa=function Td(){Sd||Ud();Sd||(Aa=Td)};
function Ud(){function a(){if(!Sd&&(Sd=!0,f.calledRun=!0,!x)){f.noFSInit||Xc||(Xc=!0,f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Zc("stdin",f.stdin):Tc("/dev/tty","/dev/stdin"),f.stdout?Zc("stdout",null,f.stdout):Tc("/dev/tty","/dev/stdout"),f.stderr?Zc("stderr",null,f.stderr):Tc("/dev/tty1","/dev/stderr"),Uc("/dev/stdin",0),Uc("/dev/stdout",1),Uc("/dev/stderr",1));Gc=!1;Ia(va);Ia(wa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Vd){var b=Od;try{var c=b(0,0);pa=c;Qa(c)}catch(d){Pa(d)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)b=f.postRun.shift(),xa.unshift(b);Ia(xa)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ia(ua);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Vd=!0;f.noInitialRun&&(Vd=!1);Ud();
